package com.clenzy.service;

import com.clenzy.model.*;
import com.clenzy.repository.*;
import com.clenzy.tenant.TenantContext;
import liquibase.*;
import liquibase.changelog.DatabaseChangeLog;
import liquibase.database.DatabaseFactory;
import liquibase.database.jvm.JdbcConnection;
import liquibase.resource.ClassLoaderResourceAccessor;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.*;
import org.springframework.transaction.support.TransactionTemplate;
import java.sql.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;

/** Migration et transactions réelles ; identité, propriété et persistance JPA des dépenses substituées. */
@EnabledIfSystemProperty(named="baitly.test.jdbc",matches="jdbc:postgresql://(localhost|127\\.0\\.0\\.1):.*")
class BaitlySupplierPurchasePostgresTest {
    static String url,user,schema;static DriverManagerDataSource source;
    NamedParameterJdbcTemplate jdbc;TransactionTemplate tx;BaitlySupplierPurchaseService service;
    TenantContext tenant;User supplier;ProviderExpenseRepository expenses;
    static final BaitlyFinancialDocument INVOICE=BaitlyFinancialDocument.checked("%PDF-1.4 Supplier invoice".getBytes());
    static final BaitlyFinancialDocument RECEIPT=BaitlyFinancialDocument.checked("%PDF-1.4 External receipt".getBytes());
    @BeforeAll static void start() throws Exception {
        url=System.getProperty("baitly.test.jdbc");user=System.getProperty("baitly.test.user","postgres");schema="baitly_supplier_"+UUID.randomUUID().toString().replace("-","");
        try(var c=DriverManager.getConnection(url,user,"");var s=c.createStatement()) {
            s.execute("CREATE SCHEMA "+schema);s.execute("SET search_path TO "+schema);
            s.execute("CREATE TABLE organizations(id bigint primary key)");s.execute("CREATE TABLE users(id bigint primary key)");
            s.execute("CREATE TABLE properties(id bigint primary key,organization_id bigint,name varchar(100))");
            s.execute("CREATE TABLE provider_expenses(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,organization_id bigint,property_id bigint,provider_id bigint,amount_ht numeric(12,2),tax_rate numeric(5,4),amount_ttc numeric(12,2),currency varchar(3),invoice_reference varchar(160),status varchar(30))");
            s.execute("INSERT INTO organizations VALUES(1),(2)");s.execute("INSERT INTO users VALUES(1),(42)");s.execute("INSERT INTO properties VALUES(1,1,'Riad'),(2,2,'Other')");
        }
        source=new DriverManagerDataSource(url+(url.contains("?")?"&":"?")+"currentSchema="+schema,user,"");
        for(int pass=0;pass<2;pass++)try(var c=source.getConnection()) {
            var db=DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(c));var resources=new ClassLoaderResourceAccessor();
            try(var master=new Liquibase("db/changelog/db.changelog-master.yaml",resources,db)) {
                var selected=new DatabaseChangeLog("db/changelog/db.changelog-master.yaml");
                selected.addChangeSet(master.getDatabaseChangeLog().getChangeSets().stream().filter(cs->cs.getId().equals("0511-supplier-purchase-paths")).findFirst().orElseThrow());
                new Liquibase(selected,resources,db).update("");
            }
        }
    }
    @AfterAll static void stop() throws Exception {
        if(schema!=null)try(var c=DriverManager.getConnection(url,user,"");var s=c.createStatement()){s.execute("DROP SCHEMA "+schema+" CASCADE");}
    }
    @BeforeEach void setup() {
        jdbc=new NamedParameterJdbcTemplate(source);tx=new TransactionTemplate(new DataSourceTransactionManager(source));
        jdbc.getJdbcTemplate().execute("TRUNCATE baitly_supplier_purchases,provider_expenses CASCADE");
        var users=mock(UserRepository.class);var admin=new User();admin.setId(1L);admin.setRole(UserRole.SUPER_ADMIN);
        supplier=new User();supplier.setId(42L);supplier.setEmail("supplier@test.invalid");supplier.setEmailVerified(true);supplier.setStatus(UserStatus.ACTIVE);supplier.setRole(UserRole.HOST);
        when(users.findByKeycloakId("admin")).thenReturn(Optional.of(admin));when(users.findByKeycloakId("supplier")).thenReturn(Optional.of(supplier));when(users.findById(42L)).thenReturn(Optional.of(supplier));
        var properties=mock(PropertyRepository.class);var property=new Property();property.setId(1L);property.setOrganizationId(1L);when(properties.findById(1L)).thenReturn(Optional.of(property));
        expenses=mock(ProviderExpenseRepository.class);when(expenses.saveAndFlush(any())).thenAnswer(invocation->{
            ProviderExpense e=invocation.getArgument(0);
            long id=jdbc.getJdbcTemplate().queryForObject("INSERT INTO provider_expenses(organization_id,property_id,provider_id,amount_ht,tax_rate,amount_ttc,currency,invoice_reference,status) VALUES(?,?,?,?,?,?,?,?,?) RETURNING id",Long.class,
                e.getOrganizationId(),e.getProperty().getId(),e.getProvider().getId(),e.getAmountHt(),e.getTaxRate(),e.getAmountTtc(),e.getCurrency(),e.getInvoiceReference(),e.getStatus().name());
            e.setId(id);return e;
        });
        tenant=mock(TenantContext.class);when(tenant.getRequiredOrganizationId()).thenReturn(1L);
        service=new BaitlySupplierPurchaseService(jdbc,users,properties,expenses,tenant,new com.fasterxml.jackson.databind.ObjectMapper().findAndRegisterModules(),mock(BaitlySupplierWorkspace.class));
    }
    BaitlySupplierPurchaseService.Request request(String ref){return new BaitlySupplierPurchaseService.Request(UUID.randomUUID(),1L,"Supplier test","supplier@test.invalid",ref,"Linge de lit",LocalDate.now(),new BigDecimal("50"),new BigDecimal("0.20"));}
    long create(String ref){return tx.execute(s->service.create(request(ref),INVOICE,"admin"));}
    String invite(long id){return tx.execute(s->service.invite(id,"admin")).substring("/supplier-invitation?token=".length());}
    void external(long id) {
        try(var urls=mockStatic(ICalUrlValidator.class)) {tx.execute(s->{service.chooseExternal(id,"https://supplier.test.invalid/pay","admin");return null;});}
    }
    @Test void invitationPoliciesExposeOnlyTheMatchingInvoiceAndAllowOnlyTheClaimedActor() throws Exception {
        long id=create("RLS");String token=invite(id);invite(create("HIDDEN"));
        String hash=java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(token.getBytes(java.nio.charset.StandardCharsets.UTF_8)));
        String role="baitly_supplier_reader_"+UUID.randomUUID().toString().replace("-","");
        try(var c=source.getConnection();var s=c.createStatement()) {
            s.execute("CREATE ROLE "+role+" NOLOGIN NOSUPERUSER NOBYPASSRLS");
            try {
                s.execute("GRANT USAGE ON SCHEMA "+schema+" TO "+role);
                s.execute("GRANT SELECT ON ALL TABLES IN SCHEMA "+schema+" TO "+role);
                s.execute("GRANT UPDATE ON baitly_supplier_purchases TO "+role);
                c.setAutoCommit(false);s.execute("SET LOCAL ROLE "+role);s.execute("SET LOCAL app.current_org='2'");
                try(var rs=s.executeQuery("SELECT count(*) FROM baitly_supplier_purchases")){rs.next();assertThat(rs.getInt(1)).isZero();}
                s.execute("SET LOCAL app.supplier_claim='"+hash+"'");s.execute("SET LOCAL app.supplier_actor='42'");
                try(var rs=s.executeQuery("SELECT id FROM baitly_supplier_purchases")){assertThat(rs.next()).isTrue();assertThat(rs.getLong(1)).isEqualTo(id);assertThat(rs.next()).isFalse();}
                assertThat(s.executeUpdate("UPDATE baitly_supplier_purchases SET beneficiary_user_id=42 WHERE id="+id)).isEqualTo(1);
                assertThatThrownBy(()->s.executeUpdate("UPDATE baitly_supplier_purchases SET beneficiary_user_id=1 WHERE id="+id)).isInstanceOf(java.sql.SQLException.class);
                c.rollback();c.setAutoCommit(true);
            }finally{if(!c.getAutoCommit())c.rollback();c.setAutoCommit(true);s.execute("DROP OWNED BY "+role);s.execute("DROP ROLE "+role);}
        }
    }
    @Test void invoiceCannotAcquireAReceiptWithoutChoosingTheExternalRoute() {
        long id=create("NULL-GUARD");
        assertThatThrownBy(()->jdbc.getJdbcTemplate().update("UPDATE baitly_supplier_purchases SET beneficiary_user_id=42 WHERE id="+id)).isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
    }
    @Test void internalInvitationDoesNotGrantMembershipAndCreatesOneExactDebtOnlyAfterAcceptance() {
        long id=create("BILL-1");String token=invite(id);
        assertThatThrownBy(()->tx.execute(s->service.prepareExpense(id,"admin"))).hasMessageContaining("accepter");
        var claimed=tx.execute(s->service.claim(token,"supplier"));assertThat(claimed.get("amount")).isEqualTo(new BigDecimal("60.00"));
        long expense=tx.execute(s->service.prepareExpense(id,"admin"));long replay=tx.execute(s->service.prepareExpense(id,"admin"));assertThat(replay).isEqualTo(expense);
        verify(expenses,times(1)).saveAndFlush(argThat(e->e.getProvider().getId()==42 && e.getStatus()==ExpenseStatus.DRAFT && e.getAmountTtc().compareTo(new BigDecimal("60"))==0));
        assertThatThrownBy(()->external(id)).hasMessageContaining("compte Baitly");
        assertThatThrownBy(()->jdbc.getJdbcTemplate().update("UPDATE provider_expenses SET provider_id=1 WHERE id="+expense)).isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
    }
    @Test void externalReceiptIsDocumentaryAndNeverCreatesAPspDebt() {
        long id=create("EXTERNAL");external(id);
        var proof=new BaitlySupplierPurchaseService.ExternalReceipt("PAYMENT-1",LocalDate.now(),new BigDecimal("60"),"EUR");
        tx.execute(s->{service.recordExternal(id,proof,RECEIPT,"admin");return null;});
        tx.execute(s->{service.recordExternal(id,proof,RECEIPT,"admin");return null;});
        assertThat(service.list("admin").getFirst().get("external_reference")).isEqualTo("PAYMENT-1");
        verifyNoInteractions(expenses);assertThatThrownBy(()->invite(id)).hasMessageContaining("externe");
        assertThatThrownBy(()->tx.execute(s->service.prepareExpense(id,"admin"))).hasMessageContaining("accepter");
    }
    @Test void anExistingExpenseCannotBeDuplicatedThroughAnInvitation() {
        long id=create("EXISTING");String token=invite(id);
        jdbc.getJdbcTemplate().update("INSERT INTO provider_expenses(organization_id,property_id,provider_id,amount_ht,tax_rate,amount_ttc,currency,invoice_reference,status) VALUES(1,1,42,50,0.20,60,'EUR','EXISTING','DRAFT')");
        tx.execute(s->service.claim(token,"supplier"));
        assertThatThrownBy(()->tx.execute(s->service.prepareExpense(id,"admin"))).hasMessageContaining("déjà");
        verifyNoInteractions(expenses);
    }
    @Test void aLinkedInvoiceCannotBeRecreatedFromTheOrdinaryExpenseRoute() {
        long id=create("OTHER-ROUTE");String token=invite(id);tx.execute(s->service.claim(token,"supplier"));
        tx.execute(s->service.prepareExpense(id,"admin"));
        assertThatThrownBy(()->jdbc.getJdbcTemplate().update("INSERT INTO provider_expenses(organization_id,property_id,provider_id,amount_ht,tax_rate,amount_ttc,currency,invoice_reference,status) VALUES(1,1,42,50,0.20,60,'EUR','OTHER-ROUTE','DRAFT')"))
            .isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
        assertThat(jdbc.getJdbcTemplate().queryForObject("SELECT count(*) FROM provider_expenses",Long.class)).isEqualTo(1L);
    }
    @Test void invoiceAloneAndWrongAmountDoNotProveExternalPayment() {
        long id=create("PROOF");external(id);
        var proof=new BaitlySupplierPurchaseService.ExternalReceipt("PAY-1",LocalDate.now(),new BigDecimal("60"),"EUR");
        assertThatThrownBy(()->tx.execute(s->{service.recordExternal(id,proof,INVOICE,"admin");return null;})).hasMessageContaining("facture seule");
        assertThatThrownBy(()->tx.execute(s->{service.recordExternal(id,new BaitlySupplierPurchaseService.ExternalReceipt("PAY-1",LocalDate.now(),new BigDecimal("59"),"EUR"),RECEIPT,"admin");return null;})).hasMessageContaining("montant exact");
        assertThat(service.list("admin").getFirst().get("external_reference")).isNull();
    }
    @Test void verifiedEmailAndUnexpiredInvitationAreRequired() {
        long id=create("IDENTITY");String old=invite(id),token=invite(id);
        assertThatThrownBy(()->tx.execute(s->service.claim(old,"supplier"))).hasMessageContaining("introuvable");
        supplier.setEmailVerified(false);assertThatThrownBy(()->tx.execute(s->service.claim(token,"supplier"))).hasMessageContaining("vérifiée");
        supplier.setEmailVerified(true);supplier.setEmail("other@test.invalid");
        assertThatThrownBy(()->tx.execute(s->service.claim(token,"supplier"))).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);
        supplier.setEmail("supplier@test.invalid");jdbc.getJdbcTemplate().update("UPDATE baitly_supplier_purchases SET invitation_expires_at=CURRENT_TIMESTAMP-interval '1 day' WHERE id="+id);
        assertThatThrownBy(()->tx.execute(s->service.claim(token,"supplier"))).hasMessageContaining("expirée");
    }
    @Test void accountActivationUsesOneDurableOperationWithoutAcceptingOrExposingTheInvoice() {
        long id=create("ACTIVATION");String token=invite(id);
        String operation=tx.execute(s->service.registrationOperation(token,"supplier@test.invalid"));
        assertThat(UUID.fromString(operation)).isNotNull();
        String repeated=tx.execute(s->service.registrationOperation(token," SUPPLIER@test.invalid "));
        assertThat(repeated).isEqualTo(operation);
        assertThatThrownBy(()->tx.execute(s->service.registrationOperation(token,"other@test.invalid"))).hasMessageContaining("adresse");
        assertThat(service.list("admin").getFirst().get("beneficiary_user_id")).isNull();
        verifyNoInteractions(expenses);
        tx.execute(s->service.claim(token,"supplier"));
        assertThatThrownBy(()->tx.execute(s->service.registrationOperation(token,"supplier@test.invalid"))).hasMessageContaining("Invitation");
    }
    @Test void duplicateInvoiceAndDuplicateExternalReceiptAreRejected() {
        long id=create("UNIQUE");assertThatThrownBy(()->create("UNIQUE")).isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
        long other=create("SECOND");external(id);external(other);
        var proof=new BaitlySupplierPurchaseService.ExternalReceipt("ONE-PAYMENT",LocalDate.now(),new BigDecimal("60"),"EUR");
        tx.execute(s->{service.recordExternal(id,proof,RECEIPT,"admin");return null;});
        assertThatThrownBy(()->tx.execute(s->{service.recordExternal(other,proof,RECEIPT,"admin");return null;})).isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
    }
    @Test void concurrentBranchesCannotBothBeChosen() throws Exception {
        long id=create("RACE");
        try(var pool=Executors.newFixedThreadPool(2)) {
            var barrier=new CyclicBarrier(2);var internal=pool.submit(()->{barrier.await();try{invite(id);return true;}catch(IllegalArgumentException e){return false;}});
            var outside=pool.submit(()->{barrier.await();try{external(id);return true;}catch(IllegalArgumentException e){return false;}});
            assertThat(List.of(internal.get(15,TimeUnit.SECONDS),outside.get(15,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);
        }
    }
    @Test void tenantAndStaffAuthorizationPrecedeFinancialWrites() {
        long id=create("ACCESS");when(tenant.getRequiredOrganizationId()).thenReturn(2L);
        assertThat(service.list("admin")).isEmpty();assertThatThrownBy(()->invite(id)).hasMessageContaining("inaccessible");
        assertThatThrownBy(()->service.document(id,false,"admin")).hasMessageContaining("inaccessible");
        assertThatThrownBy(()->service.list("supplier")).isInstanceOf(org.springframework.security.access.AccessDeniedException.class);
    }
}
