import type { GuideLabels, Lang } from './WelcomeBookView';

/**
 * Libellés statiques du livret guest (la page guest est standalone, pas i18next).
 * Partagés par la page guest (`PublicGuide`) et l'aperçu live de la config
 * (`WelcomeGuideAdmin`).
 */
export const GUIDE_LABELS: Record<Lang, GuideLabels> = {
  fr: {
    welcome: 'Bienvenue', essentials: 'Les essentiels', marketplace: 'Marketplace', explore: 'Explorer le livret',
    directions: 'Comment entrer', address: 'Adresse', neighbourhood: 'Le quartier', rateStay: 'Noter mon séjour',
    featured: 'Coup de cœur', partner: 'Partenaire', request: 'Demander',
    reviewTitle: "Comment s'est passé votre séjour ?", reviewSub: 'Votre avis aide votre hôte à s’améliorer.',
    reviewPlaceholder: 'Partagez un mot sur votre séjour (optionnel)…', send: 'Envoyer mon avis',
    thanks: 'Merci pour votre retour !',
    stay: 'Votre séjour', arrival: 'Arrivée', departure: 'Départ', guests: 'voyageur(s)',
    wifi: 'Wi-Fi', network: 'Réseau', password: 'Mot de passe', accessCode: "Code d'accès",
    accessCodeLocked: 'Disponible à votre arrivée', accessCodeLockedFrom: 'Disponible dès',
    doorUnlock: 'Ouvrir la porte', doorUnlocking: 'Ouverture…',
    doorUnlocked: 'Porte déverrouillée', doorUnlockError: "Échec de l'ouverture — réessayez",
    arrivalInstr: "Instructions d'arrivée", departureInstr: 'Instructions de départ',
    parking: 'Parking', houseRules: 'Règlement intérieur', notes: 'Bon à savoir',
    accessPhotos: "Photos d'accès",
    useful: 'Numéro utile', location: 'Adresse', viewMap: 'Itinéraire',
    copy: 'Copier', copied: 'Copié', poweredBy: 'Propulsé par',
    guestbookTitle: "Livre d'or", guestbookName: 'Votre nom', guestbookMessage: 'Votre message',
    guestbookRating: 'Votre note', guestbookSend: 'Envoyer mon avis', guestbookThanks: 'Merci pour votre message !',
    activitiesTitle: 'Expériences', book: 'Réserver', aroundMe: 'Autour de vous',
    upsellsTitle: 'Services à réserver', payCta: 'Réserver',
    paySuccess: 'Paiement réussi ! Votre demande a été transmise à votre hôte.',
    payError: "Le paiement n'a pas pu démarrer. Réessayez.",
    checkinTitle: 'Check-in en ligne', checkinCta: 'Effectuer mon check-in', checkinDone: 'Check-in déjà effectué',
    chatTitle: 'Assistant du livret', chatPlaceholder: 'Posez votre question…',
    chatGreeting: "Bonjour ! Je suis Margaux, votre concierge. Wifi, accès, bons plans — je réponds à tout.",
    chatError: "Désolé, je n'ai pas pu répondre. Réessayez.",
    ask: 'Concierge', conciergeName: 'Margaux', conciergeRole: 'Concierge IA · en ligne',
    suggest1: 'Le code wifi ?', suggest2: "L'heure du check-out ?", suggest3: 'Une bonne table ?',
    notFoundTitle: 'Lien indisponible',
    notFoundText: "Ce livret n'est pas disponible. Le lien a peut-être expiré ou le séjour est terminé.",
    unavailableTitle: 'Livret non disponible',
    unavailableExpired: "Cette réservation est révolue — le livret d'accueil n'est plus disponible.",
    unavailableNoReservation: "Ce livret d'accueil n'est pas disponible : aucune réservation associée.",
    errorText: 'Une erreur est survenue. Réessayez plus tard.',
  },
  en: {
    welcome: 'Welcome', essentials: 'The essentials', marketplace: 'Marketplace', explore: 'Explore the guide',
    directions: 'How to get in', address: 'Address', neighbourhood: 'The neighbourhood', rateStay: 'Rate my stay',
    featured: 'Favourite', partner: 'Partner', request: 'Request',
    reviewTitle: 'How was your stay?', reviewSub: 'Your feedback helps your host improve.',
    reviewPlaceholder: 'Share a word about your stay (optional)…', send: 'Send my review',
    thanks: 'Thank you for your feedback!',
    stay: 'Your stay', arrival: 'Check-in', departure: 'Check-out', guests: 'guest(s)',
    wifi: 'Wi-Fi', network: 'Network', password: 'Password', accessCode: 'Access code',
    accessCodeLocked: 'Available at check-in', accessCodeLockedFrom: 'Available from',
    doorUnlock: 'Open the door', doorUnlocking: 'Opening…',
    doorUnlocked: 'Door unlocked', doorUnlockError: 'Could not open — try again',
    arrivalInstr: 'Arrival instructions', departureInstr: 'Departure instructions',
    parking: 'Parking', houseRules: 'House rules', notes: 'Good to know',
    accessPhotos: 'Access photos',
    useful: 'Useful number', location: 'Address', viewMap: 'Directions',
    copy: 'Copy', copied: 'Copied', poweredBy: 'Powered by',
    guestbookTitle: 'Guestbook', guestbookName: 'Your name', guestbookMessage: 'Your message',
    guestbookRating: 'Your rating', guestbookSend: 'Send my review', guestbookThanks: 'Thank you for your message!',
    activitiesTitle: 'Experiences', book: 'Book', aroundMe: 'Around you',
    upsellsTitle: 'Services to book', payCta: 'Book',
    paySuccess: 'Payment successful! Your request has been sent to your host.',
    payError: 'Payment could not start. Please try again.',
    checkinTitle: 'Online check-in', checkinCta: 'Complete my check-in', checkinDone: 'Check-in already completed',
    chatTitle: 'Welcome book assistant', chatPlaceholder: 'Ask a question…',
    chatGreeting: "Hi! I'm Margaux, your concierge. Wifi, access, local tips — ask me anything.",
    chatError: 'Sorry, I could not answer. Please try again.',
    ask: 'Concierge', conciergeName: 'Margaux', conciergeRole: 'AI concierge · online',
    suggest1: 'Wifi password?', suggest2: 'Check-out time?', suggest3: 'A good place to eat?',
    notFoundTitle: 'Link unavailable',
    notFoundText: 'This guide is not available. The link may have expired or the stay is over.',
    unavailableTitle: 'Guide unavailable',
    unavailableExpired: 'This reservation is over — the welcome guide is no longer available.',
    unavailableNoReservation: 'This welcome guide is not available: no reservation linked.',
    errorText: 'Something went wrong. Please try again later.',
  },
  ar: {
    welcome: 'أهلاً وسهلاً', essentials: 'الأساسيات', marketplace: 'السوق', explore: 'استكشف الدليل',
    directions: 'كيفية الدخول', address: 'العنوان', neighbourhood: 'الحي', rateStay: 'قيّم إقامتك',
    featured: 'المفضّل', partner: 'شريك', request: 'اطلب',
    reviewTitle: 'كيف كانت إقامتك؟', reviewSub: 'رأيك يساعد مضيفك على التحسّن.',
    reviewPlaceholder: 'شارك كلمة عن إقامتك (اختياري)…', send: 'إرسال تقييمي',
    thanks: 'شكراً على ملاحظاتك!',
    stay: 'إقامتك', arrival: 'الوصول', departure: 'المغادرة', guests: 'ضيف/ضيوف',
    wifi: 'واي فاي', network: 'الشبكة', password: 'كلمة المرور', accessCode: 'رمز الدخول',
    accessCodeLocked: 'متاح عند الوصول', accessCodeLockedFrom: 'متاح ابتداءً من',
    doorUnlock: 'فتح الباب', doorUnlocking: 'جارٍ الفتح…',
    doorUnlocked: 'تم فتح الباب', doorUnlockError: 'تعذّر الفتح — حاول مجدداً',
    arrivalInstr: 'تعليمات الوصول', departureInstr: 'تعليمات المغادرة',
    parking: 'موقف السيارات', houseRules: 'قواعد المنزل', notes: 'معلومات مفيدة',
    accessPhotos: 'صور الوصول',
    useful: 'رقم مفيد', location: 'العنوان', viewMap: 'الاتجاهات',
    copy: 'نسخ', copied: 'تم النسخ', poweredBy: 'بدعم من',
    guestbookTitle: 'سجل الزوار', guestbookName: 'اسمك', guestbookMessage: 'رسالتك',
    guestbookRating: 'تقييمك', guestbookSend: 'إرسال تقييمي', guestbookThanks: 'شكرًا على رسالتك!',
    activitiesTitle: 'تجارب', book: 'احجز', aroundMe: 'حولك',
    upsellsTitle: 'خدمات للحجز', payCta: 'احجز',
    paySuccess: 'تم الدفع بنجاح! تم إرسال طلبك إلى مضيفك.',
    payError: 'تعذّر بدء الدفع. حاول مرة أخرى.',
    checkinTitle: 'تسجيل الوصول عبر الإنترنت', checkinCta: 'أكمل تسجيل وصولي', checkinDone: 'تم تسجيل الوصول',
    chatTitle: 'مساعد الدليل', chatPlaceholder: 'اطرح سؤالك…',
    chatGreeting: 'مرحبًا! أنا مارغو، مساعدتك. واي فاي، الدخول، نصائح محلية — اسألني أي شيء.',
    chatError: 'عذرًا، لم أتمكن من الإجابة. حاول مرة أخرى.',
    ask: 'مساعد', conciergeName: 'مارغو', conciergeRole: 'مساعد ذكي · متصل',
    suggest1: 'كلمة سر الواي فاي؟', suggest2: 'وقت المغادرة؟', suggest3: 'مكان جيد للأكل؟',
    notFoundTitle: 'الرابط غير متاح',
    notFoundText: 'هذا الدليل غير متاح. ربما انتهت صلاحية الرابط أو انتهت الإقامة.',
    unavailableTitle: 'الدليل غير متاح',
    unavailableExpired: 'انتهت هذه الإقامة — لم يعد دليل الاستقبال متاحًا.',
    unavailableNoReservation: 'دليل الاستقبال هذا غير متاح: لا يوجد حجز مرتبط.',
    errorText: 'حدث خطأ ما. يرجى المحاولة لاحقًا.',
  },
};
