import { createRef } from 'react';
import { MemoryRouter } from 'react-router-dom';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import FiscalProfileSection, { type FiscalProfileHandle } from './FiscalProfileSection';
import { fiscalProfileApi as api, type FiscalProfile } from '../../services/api/fiscalProfileApi';
vi.mock('react-i18next', () => ({ useTranslation: () => ({ t: (key: string) => key, i18n: { language: 'fr' } }) }));
vi.mock('../../hooks/useNotification', () => ({ useNotification: () => ({ notify: { success: vi.fn(), error: vi.fn() } }) }));
vi.mock('../../hooks/useOnboarding', () => ({ useOnboarding: () => ({ completeStep: vi.fn(), steps: [{ key: 'configure_org', completed: true }] }) }));
vi.mock('../../components/AddressAutocomplete', () => ({ AddressAutocomplete: ({ value, label, onChange, countryCode }: { value: string; label: string; onChange: (s: string) => void; countryCode: string }) => <label>{label}<input value={value} onChange={e => onChange(e.target.value)} data-country={countryCode} /></label> }));
vi.mock('../../services/api/fiscalProfileApi', () => ({ fiscalProfileApi: { get: vi.fn(), update: vi.fn() } }));
const profile = (country: string): FiscalProfile => ({ id: country === 'FR' ? 1 : null, organizationId: 7, countryCode: country, defaultCurrency: country === 'FR' ? 'EUR' : 'MAD', taxIdNumber: null, vatNumber: null, fiscalRegime: 'STANDARD', vatRegistered: country === 'FR', vatDeclarationFrequency: 'MONTHLY', invoiceLanguage: 'fr', invoicePrefix: 'FA', legalMentions: null, legalEntityName: country === 'FR' ? 'Gestion France' : null, legalAddress: null });
afterEach(() => { cleanup(); vi.resetAllMocks(); });
it('opens and saves a separate country profile without moving the French one', async () => {
  vi.mocked(api.get).mockImplementation(async country => profile(country ?? 'FR'));
  vi.mocked(api.update).mockImplementation(async (data, country) => ({ ...profile(country ?? 'FR'), ...data, id: 2 }));
  const ref = createRef<FiscalProfileHandle>();
  render(<MemoryRouter><QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><button onClick={() => ref.current?.save()}>Enregistrer</button><FiscalProfileSection ref={ref} /></QueryClientProvider></MemoryRouter>);
  await screen.findByDisplayValue('Gestion France');
  fireEvent.change(screen.getByLabelText('fiscal.profile.country'), { target: { value: 'MA' } });
  await waitFor(() => expect(api.get).toHaveBeenCalledWith('MA'));
  await waitFor(() => expect(screen.getByLabelText('fiscal.profile.legalName')).toHaveValue(''));
  expect(screen.getByRole('switch')).not.toBeChecked();
  expect(screen.getByLabelText('fiscal.profile.legalAddress')).toHaveAttribute('data-country', 'MA');
  fireEvent.change(screen.getByLabelText('fiscal.profile.legalName'), { target: { value: 'Gestion Maroc' } });
  fireEvent.change(screen.getByLabelText('fiscal.profile.legalAddress'), { target: { value: 'Adresse de test au Maroc' } });
  expect(screen.getByLabelText('fiscal.profile.country')).toBeDisabled();
  fireEvent.click(screen.getByRole('button', { name: 'Enregistrer' }));
  await waitFor(() => expect(api.update).toHaveBeenCalledWith(expect.objectContaining({ countryCode: 'MA', legalEntityName: 'Gestion Maroc', vatRegistered: false }), 'MA'));
  expect(api.update).not.toHaveBeenCalledWith(expect.anything(), 'FR');
});
vi.mock('./BaitlyFiscalSubmissions', () => ({ default: () => null }));
