/** Arabic labels for the public catalogue's stable category codes. Free-text services keep their author's label. */
export const PROVIDER_TRADE_LABELS_AR: Record<string, string> = {
  CLEANING: "التنظيف",
  LAUNDRY: "غسيل الملابس والبياضات",
  LINEN: "توفير البياضات",
  SUPPLIES: "المستهلكات",
  KEYS: "المفاتيح والاستقبال",
  LOGISTICS: "الخدمات اللوجستية",
  SECURITY: "الحراسة والأمن",
  CONCIERGE: "الكونسيرج",
  MAINTENANCE: "الصيانة",
  LOCKSMITH: "الأقفال والإصلاحات الطارئة",
  EXTERIOR: "الحدائق والمساحات الخارجية",
  POOL: "المسابح والسبا",
  PEST_CONTROL: "مكافحة الآفات",
  REGULATORY: "الفحوصات النظامية",
  RENOVATION: "الأشغال والتجديد",
  CULINARY: "الطهي",
  DRIVER: "سائق خاص",
  MOBILITY: "تأجير المركبات",
  TOURIST_GUIDE: "الإرشاد السياحي",
  ACTIVITIES: "الأنشطة والرحلات",
  WELLNESS: "العناية والاسترخاء",
  CHILDCARE: "رعاية الأطفال",
  PET_CARE: "رعاية الحيوانات",
  EQUIPMENT_RENTAL: "تأجير المعدات",
  PHOTOGRAPHY: "التصوير",
  FURNISHING: "الأثاث والديكور",
  MARKETING: "الإعلانات والتسويق",
  ADMIN_LEGAL: "الإجراءات والخدمات القانونية",
  ACCOUNTING: "المحاسبة والضرائب",
  INSURANCE: "التأمين",
  UTILITIES: "الطاقة والاتصال",
  OTHER: "خدمات أخرى",
};
