-- CI only: JDBC tables from changeset 0473, absent from Hibernate create-drop.
-- Keep this block aligned with 0473. Its ALTER TABLE columns already exist through JPA.
CREATE TABLE service_assignment_proposals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id bigint NOT NULL REFERENCES service_requests(id),
    organization_id bigint NOT NULL REFERENCES organizations(id),
    cycle integer NOT NULL CHECK (cycle > 0),
    target_type varchar(10) NOT NULL CHECK (target_type IN ('team','user')),
    target_id bigint NOT NULL,
    origin varchar(12) NOT NULL CHECK (origin IN ('AUTOMATIC','MANUAL','PUBLIC','QUOTE')),
    status varchar(12) NOT NULL CHECK (status IN ('PENDING','QUOTED','ACCEPTED','DECLINED','EXPIRED','WITHDRAWN')),
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    responded_at timestamptz,
    reminder_at timestamptz,
    reason varchar(1000),
    policy_snapshot text NOT NULL,
    agreed_amount numeric(12,2),
    agreed_currency varchar(3),
    tariff_id bigint,
    CHECK (expires_at > created_at)
);
CREATE UNIQUE INDEX service_assignment_one_pending ON service_assignment_proposals(request_id) WHERE status='PENDING';
CREATE INDEX service_assignment_due ON service_assignment_proposals(expires_at,id) WHERE status='PENDING';
CREATE INDEX service_assignment_history ON service_assignment_proposals(request_id,cycle,id);
CREATE INDEX service_assignment_recipient ON service_assignment_proposals(target_type,target_id,id) WHERE status='PENDING';
CREATE INDEX service_assignment_public ON service_requests(id) WHERE assignment_phase='PUBLIC';

CREATE TABLE service_assignment_policies (
    organization_id bigint PRIMARY KEY REFERENCES organizations(id),
    settings text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE service_assignment_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id bigint NOT NULL REFERENCES service_requests(id),
    proposal_id bigint REFERENCES service_assignment_proposals(id),
    event_key varchar(160) NOT NULL UNIQUE,
    kind varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at timestamptz,
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX service_assignment_notifications_due ON service_assignment_notifications(next_attempt_at,id) WHERE sent_at IS NULL;

