package com.clenzy.scheduler;

import com.clenzy.model.ManagementContract;
import com.clenzy.model.NotificationKey;
import com.clenzy.model.OwnerPayout;
import com.clenzy.model.PayoutScheduleConfig;
import com.clenzy.repository.ManagementContractRepository;
import com.clenzy.repository.OwnerPayoutRepository;
import com.clenzy.repository.PayoutScheduleConfigRepository;
import com.clenzy.service.AccountingService;
import com.clenzy.service.NotificationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDate;
import java.util.List;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.atLeastOnce;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class PayoutGenerationSchedulerTest {

    @Mock private PayoutScheduleConfigRepository scheduleConfigRepository;
    @Mock private ManagementContractRepository contractRepository;
    @Mock private OwnerPayoutRepository payoutRepository;
    @Mock private AccountingService accountingService;
    @Mock private NotificationService notificationService;

    private PayoutGenerationScheduler scheduler;

    @BeforeEach
    void setUp() {
        scheduler = new PayoutGenerationScheduler(scheduleConfigRepository, contractRepository,
                payoutRepository, accountingService, notificationService);
    }

    @Test
    void noConfig_doesNothing() {
        when(scheduleConfigRepository.findAll()).thenReturn(List.of());

        scheduler.generateScheduledPayouts();

        verify(payoutRepository, never()).findDistinctOrganizationIds();
    }

    @Test
    void autoGenerateDisabled_doesNothing() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(false);
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));

        scheduler.generateScheduledPayouts();

        verify(payoutRepository, never()).findDistinctOrganizationIds();
    }

    @Test
    void notInConfiguredDays_doesNothing() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(true);
        // Configure a day that won't match today
        int today = LocalDate.now().getDayOfMonth();
        int notToday = today == 1 ? 28 : 1;
        cfg.setPayoutDaysOfMonth(List.of(notToday));
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));

        scheduler.generateScheduledPayouts();

        verify(payoutRepository, never()).findDistinctOrganizationIds();
    }

    @Test
    void noOrgs_completesWithoutGeneration() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(true);
        int today = LocalDate.now().getDayOfMonth();
        cfg.setPayoutDaysOfMonth(List.of(today));
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));
        when(payoutRepository.findDistinctOrganizationIds()).thenReturn(List.of());

        scheduler.generateScheduledPayouts();

        verify(notificationService, never()).notifyAdminsAndManagersByOrgId(anyLong(), any(), anyString(), anyString(), anyString());
    }

    @Test
    void orgWithNoContracts_skip() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(true);
        int today = LocalDate.now().getDayOfMonth();
        cfg.setPayoutDaysOfMonth(List.of(today));
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));
        when(payoutRepository.findDistinctOrganizationIds()).thenReturn(List.of(1L));
        when(contractRepository.findByStatus(ManagementContract.ContractStatus.ACTIVE, 1L)).thenReturn(List.of());

        scheduler.generateScheduledPayouts();

        verify(accountingService, never()).generatePayout(anyLong(), anyLong(), any(), any());
        verify(notificationService, never()).notifyAdminsAndManagersByOrgId(anyLong(), any(), anyString(), anyString(), anyString());
    }

    @Test
    void orgWithActiveContracts_generates() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(true);
        int today = LocalDate.now().getDayOfMonth();
        cfg.setPayoutDaysOfMonth(List.of(today));
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));
        when(payoutRepository.findDistinctOrganizationIds()).thenReturn(List.of(1L));

        ManagementContract contract = new ManagementContract();
        contract.setOwnerId(10L);
        contract.setStatus(ManagementContract.ContractStatus.ACTIVE);
        when(contractRepository.findByStatus(ManagementContract.ContractStatus.ACTIVE, 1L))
                .thenReturn(List.of(contract));
        // Force periodStart < today even if today is the 1st of the month
        OwnerPayout prev = new OwnerPayout();
        prev.setPeriodEnd(LocalDate.now().minusDays(30));
        when(payoutRepository.findByOwnerId(10L, 1L)).thenReturn(List.of(prev));

        OwnerPayout payout = new OwnerPayout();
        when(accountingService.generatePayout(eq(10L), eq(1L), any(), any())).thenReturn(payout);

        scheduler.generateScheduledPayouts();

        verify(accountingService).generatePayout(eq(10L), eq(1L), any(), any());
        verify(notificationService).notifyAdminsAndManagersByOrgId(eq(1L), eq(NotificationKey.PAYOUT_BATCH_GENERATED),
                anyString(), anyString(), anyString());
    }

    @Test
    void multipleOwners_generatesPerOwner() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(true);
        int today = LocalDate.now().getDayOfMonth();
        cfg.setPayoutDaysOfMonth(List.of(today));
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));
        when(payoutRepository.findDistinctOrganizationIds()).thenReturn(List.of(1L));

        ManagementContract c1 = new ManagementContract();
        c1.setOwnerId(10L);
        ManagementContract c2 = new ManagementContract();
        c2.setOwnerId(20L);
        when(contractRepository.findByStatus(ManagementContract.ContractStatus.ACTIVE, 1L))
                .thenReturn(List.of(c1, c2));
        OwnerPayout prev = new OwnerPayout();
        prev.setPeriodEnd(LocalDate.now().minusDays(30));
        lenient().when(payoutRepository.findByOwnerId(anyLong(), anyLong())).thenReturn(List.of(prev));
        when(accountingService.generatePayout(anyLong(), eq(1L), any(), any())).thenReturn(new OwnerPayout());

        scheduler.generateScheduledPayouts();

        verify(accountingService, atLeastOnce()).generatePayout(eq(10L), eq(1L), any(), any());
        verify(accountingService, atLeastOnce()).generatePayout(eq(20L), eq(1L), any(), any());
    }

    @Test
    void existingPayouts_skipsIfFullyCovered() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(true);
        int today = LocalDate.now().getDayOfMonth();
        cfg.setPayoutDaysOfMonth(List.of(today));
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));
        when(payoutRepository.findDistinctOrganizationIds()).thenReturn(List.of(1L));

        ManagementContract c = new ManagementContract();
        c.setOwnerId(10L);
        when(contractRepository.findByStatus(ManagementContract.ContractStatus.ACTIVE, 1L))
                .thenReturn(List.of(c));

        // Last payout ends today — so periodStart >= periodEnd, skip
        OwnerPayout last = new OwnerPayout();
        last.setPeriodEnd(LocalDate.now());
        when(payoutRepository.findByOwnerId(10L, 1L)).thenReturn(List.of(last));

        scheduler.generateScheduledPayouts();

        verify(accountingService, never()).generatePayout(anyLong(), anyLong(), any(), any());
    }

    @Test
    void accountingServiceThrows_continuesOtherOwners() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(true);
        int today = LocalDate.now().getDayOfMonth();
        cfg.setPayoutDaysOfMonth(List.of(today));
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));
        when(payoutRepository.findDistinctOrganizationIds()).thenReturn(List.of(1L));

        ManagementContract c1 = new ManagementContract();
        c1.setOwnerId(10L);
        ManagementContract c2 = new ManagementContract();
        c2.setOwnerId(20L);
        when(contractRepository.findByStatus(ManagementContract.ContractStatus.ACTIVE, 1L))
                .thenReturn(List.of(c1, c2));
        OwnerPayout prev = new OwnerPayout();
        prev.setPeriodEnd(LocalDate.now().minusDays(30));
        lenient().when(payoutRepository.findByOwnerId(anyLong(), anyLong())).thenReturn(List.of(prev));

        when(accountingService.generatePayout(eq(10L), eq(1L), any(), any()))
                .thenThrow(new RuntimeException("boom"));
        when(accountingService.generatePayout(eq(20L), eq(1L), any(), any()))
                .thenReturn(new OwnerPayout());

        scheduler.generateScheduledPayouts();

        verify(accountingService, atLeastOnce()).generatePayout(eq(20L), eq(1L), any(), any());
    }

    @Test
    void orgLoopThrows_continuesOtherOrgs() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(true);
        int today = LocalDate.now().getDayOfMonth();
        cfg.setPayoutDaysOfMonth(List.of(today));
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));
        when(payoutRepository.findDistinctOrganizationIds()).thenReturn(List.of(1L, 2L));

        when(contractRepository.findByStatus(ManagementContract.ContractStatus.ACTIVE, 1L))
                .thenThrow(new RuntimeException("db boom"));

        ManagementContract c = new ManagementContract();
        c.setOwnerId(30L);
        when(contractRepository.findByStatus(ManagementContract.ContractStatus.ACTIVE, 2L))
                .thenReturn(List.of(c));
        OwnerPayout prev = new OwnerPayout();
        prev.setPeriodEnd(LocalDate.now().minusDays(30));
        lenient().when(payoutRepository.findByOwnerId(anyLong(), anyLong())).thenReturn(List.of(prev));
        when(accountingService.generatePayout(eq(30L), eq(2L), any(), any())).thenReturn(new OwnerPayout());

        scheduler.generateScheduledPayouts();

        verify(accountingService).generatePayout(eq(30L), eq(2L), any(), any());
    }

    @Test
    void notificationThrows_doesNotPropagate() {
        PayoutScheduleConfig cfg = new PayoutScheduleConfig();
        cfg.setAutoGenerateEnabled(true);
        int today = LocalDate.now().getDayOfMonth();
        cfg.setPayoutDaysOfMonth(List.of(today));
        when(scheduleConfigRepository.findAll()).thenReturn(List.of(cfg));
        when(payoutRepository.findDistinctOrganizationIds()).thenReturn(List.of(1L));

        ManagementContract c = new ManagementContract();
        c.setOwnerId(10L);
        when(contractRepository.findByStatus(ManagementContract.ContractStatus.ACTIVE, 1L)).thenReturn(List.of(c));
        OwnerPayout prev = new OwnerPayout();
        prev.setPeriodEnd(LocalDate.now().minusDays(30));
        when(payoutRepository.findByOwnerId(10L, 1L)).thenReturn(List.of(prev));
        when(accountingService.generatePayout(eq(10L), eq(1L), any(), any())).thenReturn(new OwnerPayout());

        lenient().doThrow(new RuntimeException("notify fail"))
                .when(notificationService).notifyAdminsAndManagersByOrgId(anyLong(), any(), anyString(), anyString(), anyString());

        // Should not throw
        scheduler.generateScheduledPayouts();
    }
}
