-- Yield rules v1 (F8a) — règles déclaratives d'occupation, 3 modes progressifs par org.
--
-- Modèle retenu :
--   * la table existante yield_rules (baseline 0000, moteur OCCUPANCY_THRESHOLD jamais
--     implémenté) est ÉTENDUE avec des colonnes v1 explicites — pas de nouvelle table,
--     pas de DROP. Une règle « v1 » = ruleType OCCUPANCY_THRESHOLD + comparison NON NULL.
--   * le mode (SIMULATION / SUGGEST / AUTO) est PAR ORG (yield_org_configs), pas par
--     règle : un seul cadran de confiance progressif par organisation, kill-switch = enabled.
--   * les garde-fous plancher/plafond sont PAR BIEN (colonnes sur properties) : sans les
--     deux bornes, le moteur ne touche jamais au tarif du bien (skip NO_BOUNDS journalisé).

-- 1. Colonnes v1 sur les règles de yield existantes
ALTER TABLE yield_rules ADD COLUMN IF NOT EXISTS comparison VARCHAR(10);
ALTER TABLE yield_rules ADD COLUMN IF NOT EXISTS occupancy_threshold_pct NUMERIC(5,2);
ALTER TABLE yield_rules ADD COLUMN IF NOT EXISTS window_days_ahead INTEGER;
ALTER TABLE yield_rules ADD COLUMN IF NOT EXISTS adjustment_pct NUMERIC(5,2);
ALTER TABLE yield_rules ADD COLUMN IF NOT EXISTS max_daily_change_pct NUMERIC(5,2) NOT NULL DEFAULT 10;

-- 2. Garde-fous tarifaires par bien (obligatoires pour que le yield agisse sur le bien)
ALTER TABLE properties ADD COLUMN IF NOT EXISTS yield_price_floor NUMERIC(10,2);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS yield_price_ceiling NUMERIC(10,2);

-- 3. Config yield par organisation : kill-switch + mode progressif
CREATE TABLE IF NOT EXISTS yield_org_configs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT      NOT NULL UNIQUE,
    enabled         BOOLEAN     NOT NULL DEFAULT FALSE,
    mode            VARCHAR(20) NOT NULL DEFAULT 'SIMULATION',
    created_at      TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP
);
