-- Journal des ajustements yield v1 (F8a) — replay complet possible.
--
-- Une ligne par (bien, date tarifaire, jour d'évaluation) : prix avant / après (ou
-- proposé), mode (SIMULATED / SUGGESTED / APPLIED), occupation constatée + seuil,
-- lien suggestion HITL (mode SUGGEST), skip_reason pour les non-actions journalisées
-- (NO_BOUNDS, DAILY_CAP_REACHED, EVALUATION_ERROR — target_date NULL dans ce cas).
--
-- Concurrence : l'index unique PARTIEL ci-dessous garantit qu'un même tarif
-- (bien + date tarifaire) n'est APPLIQUÉ qu'une fois par jour calendaire — un
-- double-run concurrent (scheduler + apply HITL) échoue sur l'index et est
-- journalisé en DAILY_CAP_REACHED, jamais appliqué deux fois (pas de check-then-act nu).

CREATE TABLE IF NOT EXISTS yield_adjustments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id  BIGINT       NOT NULL,
    property_id      BIGINT       NOT NULL,
    rule_id          BIGINT,
    target_date      DATE,
    adjustment_day   DATE         NOT NULL,
    mode             VARCHAR(20)  NOT NULL,
    price_before     NUMERIC(10,2),
    price_after      NUMERIC(10,2),
    occupancy_pct    NUMERIC(5,2),
    threshold_pct    NUMERIC(5,2),
    comparison       VARCHAR(10),
    reason           VARCHAR(300),
    suggestion_id    BIGINT,
    skip_reason      VARCHAR(40),
    created_at       TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_yield_adjustments_org_created
    ON yield_adjustments (organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_yield_adjustments_prop_day
    ON yield_adjustments (property_id, adjustment_day);

-- Garantie « un ajustement APPLIQUÉ par bien / date tarifaire / jour » (anti double-apply)
CREATE UNIQUE INDEX IF NOT EXISTS ux_yield_adjustments_applied_once
    ON yield_adjustments (property_id, target_date, adjustment_day)
    WHERE mode = 'APPLIED';
