-- Baitly: source exports are encrypted by EncryptedFieldConverter, never JSONB/plaintext.
CREATE TABLE pms_import_batches (
    id UUID PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    created_by VARCHAR(255) NOT NULL,
    source VARCHAR(80) NOT NULL,
    source_account VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'COMPLETED')),
    payload TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_pms_import_batches_org_actor ON pms_import_batches(organization_id, created_by, created_at DESC);
CREATE TABLE pms_import_bindings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    source_key VARCHAR(64) NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    target_id BIGINT NOT NULL,
    batch_id UUID NOT NULL REFERENCES pms_import_batches(id),
    CONSTRAINT uq_pms_import_binding UNIQUE (organization_id, source_key)
);
ALTER TABLE reservations ADD COLUMN migration_automation_paused BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE pms_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE pms_import_batches FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pms_import_batches
    USING (current_setting('app.bypass_rls', true) = 'on'
        OR organization_id = NULLIF(current_setting('app.current_org', true), '')::bigint)
    WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
        OR organization_id = NULLIF(current_setting('app.current_org', true), '')::bigint);
ALTER TABLE pms_import_bindings ENABLE ROW LEVEL SECURITY;
ALTER TABLE pms_import_bindings FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON pms_import_bindings
    USING (current_setting('app.bypass_rls', true) = 'on'
        OR organization_id = NULLIF(current_setting('app.current_org', true), '')::bigint)
    WITH CHECK (current_setting('app.bypass_rls', true) = 'on'
        OR organization_id = NULLIF(current_setting('app.current_org', true), '')::bigint);
