-- Baitly : preuves documentaires OTA, séparées des encaissements et des fonds PSP.
CREATE TABLE baitly_ota_settlements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id),
    request_id uuid NOT NULL,
    fingerprint varchar(64) NOT NULL,
    channel varchar(100) NOT NULL,
    ota_reference varchar(160) NOT NULL,
    bank_reference varchar(160) NOT NULL,
    beneficiary_user_id bigint REFERENCES users(id),
    beneficiary_name varchar(255) NOT NULL,
    currency varchar(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    received_on date NOT NULL,
    net numeric(14,2) NOT NULL CHECK (net > 0),
    statement bytea NOT NULL CHECK (octet_length(statement) BETWEEN 8 AND 5242880),
    statement_mime varchar(30) NOT NULL,
    statement_sha256 varchar(64) NOT NULL,
    bank_receipt bytea NOT NULL CHECK (octet_length(bank_receipt) BETWEEN 8 AND 5242880),
    bank_mime varchar(30) NOT NULL,
    bank_sha256 varchar(64) NOT NULL,
    recorded_by bigint NOT NULL REFERENCES users(id),
    recorded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(organization_id, request_id)
);
CREATE TABLE baitly_ota_settlement_lines (
    settlement_id bigint NOT NULL REFERENCES baitly_ota_settlements(id),
    organization_id bigint NOT NULL REFERENCES organizations(id),
    reservation_id bigint NOT NULL REFERENCES reservations(id),
    gross numeric(14,2) NOT NULL CHECK(gross > 0),
    fees numeric(14,2) NOT NULL CHECK(fees >= 0),
    refunds numeric(14,2) NOT NULL CHECK(refunds >= 0),
    net numeric(14,2) NOT NULL CHECK(net > 0 AND net = gross - fees - refunds),
    PRIMARY KEY(settlement_id,reservation_id)
);
CREATE INDEX idx_baitly_ota_settlement_reservation ON baitly_ota_settlement_lines(organization_id,reservation_id);
CREATE TABLE baitly_ota_settlement_voids (
    settlement_id bigint PRIMARY KEY REFERENCES baitly_ota_settlements(id),
    organization_id bigint NOT NULL REFERENCES organizations(id),
    reason varchar(500) NOT NULL CHECK(length(trim(reason)) >= 10),
    recorded_by bigint NOT NULL REFERENCES users(id),
    recorded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_baitly_ota_bank_reference ON baitly_ota_settlements(organization_id,bank_reference);
CREATE INDEX idx_baitly_ota_channel_reference ON baitly_ota_settlements(organization_id,channel,ota_reference);
CREATE FUNCTION baitly_ota_active_reference_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM pg_advisory_xact_lock(hashtextextended('ota-bank:'||NEW.organization_id::text||':'||NEW.bank_reference,0));
    PERFORM pg_advisory_xact_lock(hashtextextended('ota-statement:'||NEW.organization_id::text||':'||NEW.channel||':'||NEW.ota_reference,0));
    IF EXISTS(SELECT 1 FROM baitly_ota_settlements s WHERE s.organization_id=NEW.organization_id
        AND (s.bank_reference=NEW.bank_reference OR (s.channel=NEW.channel AND s.ota_reference=NEW.ota_reference))
        AND NOT EXISTS(SELECT 1 FROM baitly_ota_settlement_voids v WHERE v.settlement_id=s.id)) THEN
        RAISE EXCEPTION 'Bank or OTA receipt already matched' USING ERRCODE='23505';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER baitly_ota_active_reference_guard BEFORE INSERT ON baitly_ota_settlements
    FOR EACH ROW EXECUTE FUNCTION baitly_ota_active_reference_guard();
CREATE FUNCTION baitly_ota_evidence_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'Documentary evidence is immutable' USING ERRCODE='23514';
    END IF;
    IF TG_TABLE_NAME <> 'baitly_ota_settlements' AND NOT EXISTS(
        SELECT 1 FROM baitly_ota_settlements s WHERE s.id=NEW.settlement_id AND s.organization_id=NEW.organization_id) THEN
        RAISE EXCEPTION 'Settlement outside organization' USING ERRCODE='23514';
    END IF;
    IF TG_TABLE_NAME = 'baitly_ota_settlement_lines' THEN
        IF NOT EXISTS(SELECT 1 FROM reservations r WHERE r.id=NEW.reservation_id AND r.organization_id=NEW.organization_id) THEN
            RAISE EXCEPTION 'Reservation outside organization' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER baitly_ota_evidence_immutable BEFORE UPDATE OR DELETE ON baitly_ota_settlements FOR EACH ROW EXECUTE FUNCTION baitly_ota_evidence_guard();
CREATE TRIGGER baitly_ota_line_guard BEFORE INSERT OR UPDATE OR DELETE ON baitly_ota_settlement_lines FOR EACH ROW EXECUTE FUNCTION baitly_ota_evidence_guard();
CREATE TRIGGER baitly_ota_void_guard BEFORE INSERT OR UPDATE OR DELETE ON baitly_ota_settlement_voids FOR EACH ROW EXECUTE FUNCTION baitly_ota_evidence_guard();
CREATE FUNCTION baitly_ota_total_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE settlement bigint;
BEGIN
    IF TG_TABLE_NAME='baitly_ota_settlements' THEN settlement=NEW.id; ELSE settlement=NEW.settlement_id; END IF;
    IF EXISTS(SELECT 1 FROM baitly_ota_settlements s WHERE s.id=settlement
        AND s.net <> (SELECT COALESCE(sum(l.net),0) FROM baitly_ota_settlement_lines l WHERE l.settlement_id=s.id)) THEN
        RAISE EXCEPTION 'OTA statement and allocations must balance' USING ERRCODE='23514';
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER baitly_ota_total AFTER INSERT ON baitly_ota_settlements
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION baitly_ota_total_guard();
CREATE CONSTRAINT TRIGGER baitly_ota_lines_total AFTER INSERT ON baitly_ota_settlement_lines
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION baitly_ota_total_guard();
ALTER TABLE baitly_ota_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE baitly_ota_settlements FORCE ROW LEVEL SECURITY;
ALTER TABLE baitly_ota_settlement_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE baitly_ota_settlement_lines FORCE ROW LEVEL SECURITY;
ALTER TABLE baitly_ota_settlement_voids ENABLE ROW LEVEL SECURITY;
ALTER TABLE baitly_ota_settlement_voids FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON baitly_ota_settlements
 USING(current_setting('app.bypass_rls',true)='on' OR organization_id=NULLIF(current_setting('app.current_org',true),'')::bigint)
 WITH CHECK(current_setting('app.bypass_rls',true)='on' OR organization_id=NULLIF(current_setting('app.current_org',true),'')::bigint);
CREATE POLICY tenant_isolation ON baitly_ota_settlement_lines
 USING(current_setting('app.bypass_rls',true)='on' OR organization_id=NULLIF(current_setting('app.current_org',true),'')::bigint)
 WITH CHECK(current_setting('app.bypass_rls',true)='on' OR organization_id=NULLIF(current_setting('app.current_org',true),'')::bigint);
CREATE POLICY tenant_isolation ON baitly_ota_settlement_voids
 USING(current_setting('app.bypass_rls',true)='on' OR organization_id=NULLIF(current_setting('app.current_org',true),'')::bigint)
 WITH CHECK(current_setting('app.bypass_rls',true)='on' OR organization_id=NULLIF(current_setting('app.current_org',true),'')::bigint);
