-- Baitly : achat fournisseur distinct d'un remboursement de frais prestataire.
CREATE TABLE baitly_supplier_purchases (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organization_id bigint NOT NULL REFERENCES organizations(id),
 property_id bigint NOT NULL REFERENCES properties(id),
 request_id uuid NOT NULL,
 fingerprint varchar(64) NOT NULL,
 supplier_name varchar(200) NOT NULL,
 supplier_email_hash varchar(64) NOT NULL,
 invoice_reference varchar(160) NOT NULL,
 description varchar(500) NOT NULL,
 expense_date date NOT NULL,
 amount_ht numeric(12,2) NOT NULL CHECK(amount_ht>0),
 tax_rate numeric(5,4) NOT NULL CHECK(tax_rate BETWEEN 0 AND 1),
 amount_ttc numeric(12,2) NOT NULL CHECK(amount_ttc=amount_ht+round(amount_ht*tax_rate,2)),
 currency varchar(3) NOT NULL CHECK(currency='EUR'),
 invoice bytea NOT NULL CHECK(octet_length(invoice) BETWEEN 8 AND 5242880),
 invoice_sha256 varchar(64) NOT NULL,
 mode varchar(20) CHECK(mode IN ('BAITLY','EXTERNAL')),
 invitation_hash varchar(64),
 invitation_expires_at timestamptz,
 registration_operation uuid NOT NULL DEFAULT gen_random_uuid(),
 beneficiary_user_id bigint REFERENCES users(id),
 expense_id bigint UNIQUE REFERENCES provider_expenses(id),
 external_url varchar(2000),
 external_reference varchar(160),
 external_received_on date,
 external_receipt bytea CHECK(octet_length(external_receipt) BETWEEN 8 AND 5242880),
 external_receipt_sha256 varchar(64),
 external_recorded_by bigint REFERENCES users(id),
 created_by bigint NOT NULL REFERENCES users(id),
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(organization_id,request_id),
 UNIQUE(organization_id,supplier_email_hash,invoice_reference),
 UNIQUE(organization_id,external_reference),
 CHECK (COALESCE((mode='BAITLY' AND external_reference IS NULL AND external_url IS NULL AND external_receipt IS NULL)
     OR (mode='EXTERNAL' AND beneficiary_user_id IS NULL AND expense_id IS NULL AND invitation_hash IS NULL)
     OR (mode IS NULL AND beneficiary_user_id IS NULL AND expense_id IS NULL AND invitation_hash IS NULL AND external_receipt IS NULL AND external_url IS NULL AND external_reference IS NULL),false)),
 CHECK ((external_reference IS NULL AND external_received_on IS NULL AND external_receipt IS NULL AND external_recorded_by IS NULL)
     OR (external_reference IS NOT NULL AND external_received_on IS NOT NULL AND external_receipt IS NOT NULL AND external_recorded_by IS NOT NULL))
);
CREATE UNIQUE INDEX idx_baitly_supplier_invitation ON baitly_supplier_purchases(invitation_hash) WHERE invitation_hash IS NOT NULL;
CREATE FUNCTION baitly_supplier_purchase_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Purchase evidence cannot be deleted' USING ERRCODE='23514'; END IF;
 IF TG_OP='UPDATE' THEN
  IF ROW(NEW.organization_id,NEW.property_id,NEW.request_id,NEW.fingerprint,NEW.supplier_name,NEW.supplier_email_hash,
       NEW.invoice_reference,NEW.description,NEW.expense_date,NEW.amount_ht,NEW.tax_rate,NEW.amount_ttc,NEW.currency,NEW.invoice,NEW.invoice_sha256,NEW.created_by,NEW.created_at,NEW.registration_operation)
     IS DISTINCT FROM ROW(OLD.organization_id,OLD.property_id,OLD.request_id,OLD.fingerprint,OLD.supplier_name,OLD.supplier_email_hash,
       OLD.invoice_reference,OLD.description,OLD.expense_date,OLD.amount_ht,OLD.tax_rate,OLD.amount_ttc,OLD.currency,OLD.invoice,OLD.invoice_sha256,OLD.created_by,OLD.created_at,OLD.registration_operation)
     OR (OLD.mode IS NOT NULL AND NEW.mode IS DISTINCT FROM OLD.mode)
     OR (OLD.beneficiary_user_id IS NOT NULL AND NEW.beneficiary_user_id IS DISTINCT FROM OLD.beneficiary_user_id)
     OR (OLD.expense_id IS NOT NULL AND NEW.expense_id IS DISTINCT FROM OLD.expense_id)
     OR (OLD.external_reference IS NOT NULL AND ROW(NEW.external_reference,NEW.external_received_on,NEW.external_receipt,NEW.external_receipt_sha256,NEW.external_recorded_by)
         IS DISTINCT FROM ROW(OLD.external_reference,OLD.external_received_on,OLD.external_receipt,OLD.external_receipt_sha256,OLD.external_recorded_by)) THEN
   RAISE EXCEPTION 'Purchase identity or payment path is frozen' USING ERRCODE='23514';
  END IF;
 END IF;
 IF TG_OP='INSERT' OR NEW.expense_id IS DISTINCT FROM OLD.expense_id THEN
  IF NOT EXISTS(SELECT 1 FROM properties p WHERE p.id=NEW.property_id AND p.organization_id=NEW.organization_id) THEN
   RAISE EXCEPTION 'Property outside purchase organization' USING ERRCODE='23514';
  END IF;
 END IF;
 IF NEW.expense_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM provider_expenses e WHERE e.id=NEW.expense_id
    AND e.organization_id=NEW.organization_id AND e.property_id=NEW.property_id AND e.provider_id=NEW.beneficiary_user_id
    AND e.amount_ht=NEW.amount_ht AND e.amount_ttc=NEW.amount_ttc AND e.tax_rate=NEW.tax_rate AND e.currency=NEW.currency) THEN
  RAISE EXCEPTION 'Expense does not match supplier invoice' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER baitly_supplier_purchase_guard BEFORE INSERT OR UPDATE OR DELETE ON baitly_supplier_purchases
 FOR EACH ROW EXECUTE FUNCTION baitly_supplier_purchase_guard();
CREATE FUNCTION baitly_supplier_expense_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF EXISTS(SELECT 1 FROM baitly_supplier_purchases p WHERE p.expense_id=OLD.id)
   AND ROW(NEW.organization_id,NEW.provider_id,NEW.property_id,NEW.amount_ht,NEW.amount_ttc,NEW.tax_rate,NEW.currency,NEW.invoice_reference)
       IS DISTINCT FROM ROW(OLD.organization_id,OLD.provider_id,OLD.property_id,OLD.amount_ht,OLD.amount_ttc,OLD.tax_rate,OLD.currency,OLD.invoice_reference) THEN
  RAISE EXCEPTION 'Supplier purchase creditor and amount are immutable' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER baitly_supplier_expense_guard BEFORE UPDATE ON provider_expenses FOR EACH ROW EXECUTE FUNCTION baitly_supplier_expense_guard();
-- Toutes les écritures de dépenses concurrentes utilisent la même clé de facture.
CREATE FUNCTION baitly_supplier_invoice_once() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.invoice_reference IS NOT NULL AND NEW.invoice_reference<>'' THEN
  PERFORM pg_advisory_xact_lock(hashtextextended(NEW.organization_id::text || ':' || NEW.provider_id::text || ':' || NEW.invoice_reference,0));
  IF EXISTS(SELECT 1 FROM baitly_supplier_purchases p WHERE p.organization_id=NEW.organization_id
       AND p.beneficiary_user_id=NEW.provider_id AND p.invoice_reference=NEW.invoice_reference)
    AND EXISTS(SELECT 1 FROM provider_expenses e WHERE e.organization_id=NEW.organization_id
       AND e.provider_id=NEW.provider_id AND e.invoice_reference=NEW.invoice_reference AND e.id<>NEW.id) THEN
   RAISE EXCEPTION 'Supplier invoice already has an expense' USING ERRCODE='23514';
  END IF;
 END IF;
 RETURN NEW;
END;
$$;
CREATE TRIGGER baitly_supplier_invoice_once BEFORE INSERT OR UPDATE OF provider_id,invoice_reference ON provider_expenses
 FOR EACH ROW EXECUTE FUNCTION baitly_supplier_invoice_once();
ALTER TABLE baitly_supplier_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE baitly_supplier_purchases FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON baitly_supplier_purchases
 USING(current_setting('app.bypass_rls',true)='on' OR organization_id=NULLIF(current_setting('app.current_org',true),'')::bigint)
 WITH CHECK(current_setting('app.bypass_rls',true)='on' OR organization_id=NULLIF(current_setting('app.current_org',true),'')::bigint);
-- Une invitation ne crée aucun rôle ni rattachement d'organisation. Le serveur pose ces valeurs après vérification de l'identité.
CREATE POLICY supplier_claim_read ON baitly_supplier_purchases FOR SELECT
 USING(mode='BAITLY' AND invitation_expires_at>CURRENT_TIMESTAMP
   AND invitation_hash=current_setting('app.supplier_claim',true));
CREATE POLICY supplier_claim_accept ON baitly_supplier_purchases FOR UPDATE
 USING(mode='BAITLY' AND invitation_expires_at>CURRENT_TIMESTAMP AND invitation_hash=current_setting('app.supplier_claim',true))
 WITH CHECK(mode='BAITLY' AND invitation_hash=current_setting('app.supplier_claim',true)
   AND beneficiary_user_id=NULLIF(current_setting('app.supplier_actor',true),'')::bigint);
