-- Baitly : conserver les statuts PULL avant de les acquitter chez le partenaire.
CREATE TABLE baitly_iopole_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    environment VARCHAR(10) NOT NULL CHECK (environment IN ('SANDBOX', 'LIVE')),
    customer_id UUID NOT NULL,
    status_id UUID NOT NULL,
    invoice_id UUID NOT NULL,
    body TEXT NOT NULL,
    UNIQUE (environment, customer_id, status_id)
);
CREATE INDEX ix_baitly_iopole_invoice ON baitly_iopole_statuses (organization_id, environment, customer_id, invoice_id);

CREATE FUNCTION baitly_iopole_status_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Iopole status is immutable';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_baitly_iopole_status_immutable BEFORE UPDATE OR DELETE ON baitly_iopole_statuses
    FOR EACH ROW EXECUTE FUNCTION baitly_iopole_status_immutable();
