-- Baitly : archives CII distinctes des factures émises (invoices).
CREATE TABLE baitly_invoice_fiscal_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    source_hash VARCHAR(64) NOT NULL,
    document_hash VARCHAR(64) NOT NULL,
    preparation TEXT NOT NULL,
    xml TEXT NOT NULL,
    validation VARCHAR(120) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (organization_id, invoice_id)
);
CREATE FUNCTION baitly_invoice_fiscal_document_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Baitly fiscal document is immutable';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_baitly_invoice_fiscal_document_immutable BEFORE UPDATE OR DELETE ON baitly_invoice_fiscal_documents
    FOR EACH ROW EXECUTE FUNCTION baitly_invoice_fiscal_document_immutable();
