/** Photographies génériques Baitly. L'ordre des références correspond aux cellules des planches 4 × 4. */
export type InventorySeed = readonly [key: string, fr: string, en: string, ar: string];
export interface InventorySheet { key: string; room: string; items: readonly InventorySeed[] }
export const INVENTORY_SHEETS: readonly InventorySheet[] = [
  { key: 'seating', room: 'Salon', items: [
    ['sofa-two', 'Canapé 2 places', 'Two-seat fabric sofa', 'أريكة بمقعدين'],
    ['sofa-three', 'Canapé 3 places', 'Three-seat fabric sofa', 'أريكة بثلاثة مقاعد'],
    ['corner-sofa', 'Canapé d’angle', 'L-shaped corner sofa', 'أريكة زاوية'],
    ['sofa-bed', 'Canapé convertible', 'Sofa bed unfolded into a bed', 'أريكة تتحول إلى سرير'],
    ['futon', 'Banquette clic-clac', 'Foldable futon sofa', 'أريكة سرير قابلة للطي'],
    ['armchair', 'Fauteuil', 'Upholstered armchair', 'كرسي بذراعين'],
    ['recliner', 'Fauteuil relax', 'Reclining armchair with extended footrest', 'كرسي استرخاء'],
    ['rocking-chair', 'Fauteuil à bascule', 'Wooden rocking chair', 'كرسي هزاز'],
    ['dining-chair', 'Chaise de salle à manger', 'Wooden dining chair', 'كرسي طعام'],
    ['folding-chair', 'Chaise pliante', 'Folding chair', 'كرسي قابل للطي'],
    ['bar-stool', 'Tabouret de bar', 'Tall bar stool', 'مقعد بار مرتفع'],
    ['stool', 'Tabouret bas', 'Low wooden stool', 'مقعد خشبي منخفض'],
    ['bench', 'Banc', 'Wooden indoor bench', 'مقعد طويل'],
    ['pouffe', 'Pouf', 'Round upholstered pouffe', 'مسند جلوس مبطن'],
    ['beanbag', 'Pouf poire', 'Large beanbag chair', 'كرسي كيس حبيبات'],
    ['moroccan-bench', 'Banquette de salon marocain', 'Low Moroccan salon bench with patterned cushions', 'جلسة صالون مغربي'],
  ] },
  { key: 'furniture', room: 'Salon', items: [
    ['dining-table', 'Table à manger rectangulaire', 'Rectangular wooden dining table', 'طاولة طعام مستطيلة'],
    ['round-table', 'Table à manger ronde', 'Round dining table', 'طاولة طعام مستديرة'],
    ['extendable-table', 'Table à rallonges', 'Extendable table with extension leaf exposed', 'طاولة قابلة للتمديد'],
    ['coffee-table', 'Table basse', 'Low coffee table', 'طاولة قهوة منخفضة'],
    ['nesting-tables', 'Tables gigognes', 'Three nesting side tables', 'طاولات متداخلة'],
    ['side-table', 'Table d’appoint', 'Small side table', 'طاولة جانبية'],
    ['console-table', 'Console d’entrée', 'Narrow hallway console table', 'طاولة مدخل ضيقة'],
    ['tv-unit', 'Meuble TV', 'Low television cabinet without television', 'خزانة تلفاز'],
    ['sideboard', 'Buffet', 'Wooden sideboard cabinet', 'خزانة جانبية'],
    ['display-cabinet', 'Vitrine', 'Glass-front display cabinet', 'خزانة عرض زجاجية'],
    ['bookcase', 'Bibliothèque', 'Tall open bookcase', 'مكتبة رفوف'],
    ['desk', 'Bureau', 'Writing desk with drawer', 'مكتب'],
    ['office-chair', 'Chaise de bureau', 'Ergonomic office chair with wheels', 'كرسي مكتب بعجلات'],
    ['dressing-table', 'Coiffeuse', 'Dressing table with mirror', 'طاولة زينة بمرآة'],
    ['bedside-table', 'Table de chevet', 'Bedside table with drawer', 'طاولة بجانب السرير'],
    ['chest-drawers', 'Commode', 'Chest of drawers', 'خزانة أدراج'],
  ] },
  { key: 'beds', room: 'Chambre', items: [
    ['single-bed', 'Lit simple 90 × 200', 'Single bed with narrow mattress', 'سرير فردي 90 × 200'],
    ['double-bed', 'Lit double 140 × 200', 'Double bed with two pillows', 'سرير مزدوج 140 × 200'],
    ['queen-bed', 'Lit queen size 160 × 200', 'Queen size bed with broad padded headboard', 'سرير كوين 160 × 200'],
    ['king-bed', 'Lit king size 180 × 200', 'Very wide king size bed with four pillows', 'سرير كينغ 180 × 200'],
    ['twin-beds', 'Deux lits jumeaux', 'Two separate matching single beds', 'سريران فرديان متماثلان'],
    ['bunk-bed', 'Lits superposés', 'Wooden bunk bed with ladder', 'سرير بطابقين'],
    ['trundle-bed', 'Lit gigogne', 'Trundle bed with lower bed pulled out', 'سرير بسحب سفلي'],
    ['loft-bed', 'Lit mezzanine', 'Loft bed with clear empty space below', 'سرير مرتفع'],
    ['folding-bed', 'Lit d’appoint pliant', 'Folding guest bed partly unfolded', 'سرير إضافي قابل للطي'],
    ['murphy-bed', 'Lit escamotable', 'Wall bed lowered from its cabinet', 'سرير جداري قابل للطي'],
    ['storage-bed', 'Lit coffre', 'Storage bed with mattress base lifted', 'سرير مع صندوق تخزين'],
    ['inflatable-bed', 'Matelas gonflable', 'Inflatable guest air mattress', 'مرتبة هوائية'],
    ['spring-mattress', 'Matelas à ressorts', 'Thick spring mattress standing on edge', 'مرتبة بنوابض'],
    ['foam-mattress', 'Matelas en mousse', 'Foam mattress with flat cream quilted cover', 'مرتبة إسفنجية'],
    ['slatted-base', 'Sommier à lattes', 'Bare wooden slatted bed base', 'قاعدة سرير بشرائح خشبية'],
    ['headboard', 'Tête de lit', 'Freestanding padded headboard only', 'لوح رأس السرير'],
  ] },
  { key: 'textiles', room: 'Chambre', items: [
    ['mattress-topper', 'Surmatelas', 'Thick mattress topper rolled halfway', 'لبادة مرتبة'],
    ['waterproof-protector', 'Alèse imperméable', 'Waterproof mattress protector with elastic corners', 'واقي مرتبة مقاوم للماء'],
    ['bolster', 'Traversin', 'Long cylindrical white bolster pillow', 'وسادة أسطوانية طويلة'],
    ['ergonomic-pillow', 'Oreiller ergonomique', 'Contoured memory foam pillow', 'وسادة طبية محدبة'],
    ['decorative-cushion', 'Coussin décoratif', 'Square decorative linen cushion', 'وسادة زينة مربعة'],
    ['cushion-cover', 'Housse de coussin', 'Empty cushion cover with visible zipper', 'غطاء وسادة زينة'],
    ['bedspread', 'Couvre-lit', 'Folded quilted bedspread', 'مفرش سرير مبطن'],
    ['throw', 'Plaid', 'Folded knitted throw blanket with tassels', 'بطانية خفيفة محبوكة'],
    ['blackout-curtains', 'Rideaux occultants', 'Pair of heavy opaque curtains on short rod', 'ستائر معتمة'],
    ['sheer-curtains', 'Voilages', 'Pair of translucent sheer curtains', 'ستائر شفافة'],
    ['roller-blind', 'Store enrouleur', 'Partly lowered roller blind', 'ستارة رول'],
    ['venetian-blind', 'Store vénitien', 'Venetian slatted blind', 'ستارة شرائح'],
    ['rug', 'Tapis de salon', 'Rectangular woven living room rug', 'سجادة غرفة جلوس'],
    ['runner-rug', 'Tapis de couloir', 'Long narrow hallway runner rug', 'سجادة ممر طويلة'],
    ['doormat', 'Paillasson', 'Coir entrance doormat without writing', 'حصيرة مدخل'],
    ['mosquito-net', 'Moustiquaire de lit', 'Suspended canopy mosquito net', 'ناموسية سرير'],
  ] },
  { key: 'large-appliances', room: 'Cuisine', items: [
    ['fridge', 'Réfrigérateur', 'Tall single-door refrigerator slightly open', 'ثلاجة بباب واحد'],
    ['fridge-freezer', 'Réfrigérateur combiné', 'Tall refrigerator with separate bottom freezer', 'ثلاجة مع مجمد سفلي'],
    ['american-fridge', 'Réfrigérateur américain', 'Wide side-by-side refrigerator with water dispenser', 'ثلاجة أمريكية ببابين'],
    ['mini-fridge', 'Mini-réfrigérateur', 'Compact minibar refrigerator', 'ثلاجة صغيرة'],
    ['upright-freezer', 'Congélateur armoire', 'Upright freezer with drawers visible', 'مجمد عمودي'],
    ['chest-freezer', 'Congélateur coffre', 'Chest freezer with top lid open', 'مجمد صندوقي'],
    ['dishwasher', 'Lave-vaisselle', 'Full-size dishwasher with front door open', 'غسالة صحون كبيرة'],
    ['mini-dishwasher', 'Mini-lave-vaisselle', 'Small countertop dishwasher', 'غسالة صحون صغيرة'],
    ['oven', 'Four encastrable', 'Built-in electric oven', 'فرن كهربائي مدمج'],
    ['microwave', 'Four à micro-ondes', 'Countertop microwave oven', 'فرن ميكروويف'],
    ['mini-oven', 'Mini-four', 'Countertop mini oven with heating coils', 'فرن صغير'],
    ['gas-stove', 'Cuisinière à gaz', 'Freestanding cooker with gas burners and oven', 'موقد غاز مع فرن'],
    ['induction-hob', 'Plaque à induction', 'Black induction hob with four smooth cooking rings', 'موقد حث كهربائي'],
    ['ceramic-hob', 'Plaque vitrocéramique', 'Ceramic hob with glowing red radiant rings', 'موقد زجاجي سيراميكي'],
    ['gas-hob', 'Plaque de cuisson à gaz', 'Four burner gas hob with metal pan supports', 'موقد غاز بأربع شعلات'],
    ['extractor-hood', 'Hotte aspirante', 'Stainless steel chimney extractor hood', 'شفاط مطبخ'],
  ] },
  { key: 'small-appliances', room: 'Cuisine', items: [
    ['toaster', 'Grille-pain', 'Two-slot toaster', 'محمصة خبز'],
    ['blender', 'Blender', 'Countertop blender with glass jug', 'خلاط بإبريق'],
    ['hand-blender', 'Mixeur plongeant', 'Handheld immersion blender', 'خلاط يدوي غاطس'],
    ['hand-mixer', 'Batteur électrique', 'Electric hand mixer with twin beaters', 'مضرب كهربائي يدوي'],
    ['stand-mixer', 'Robot pâtissier', 'Stand mixer with stainless bowl', 'عجانة كهربائية'],
    ['food-processor', 'Robot multifonction', 'Food processor with chopping bowl', 'محضر طعام'],
    ['air-fryer', 'Friteuse à air', 'Basket air fryer with drawer open', 'قلاية هوائية'],
    ['deep-fryer', 'Friteuse à huile', 'Oil deep fryer with metal basket', 'قلاية زيت'],
    ['rice-cooker', 'Cuiseur à riz', 'Electric rice cooker with lid open', 'طباخة أرز'],
    ['steamer', 'Cuiseur vapeur', 'Three-tier electric food steamer', 'طباخة بخار'],
    ['multicooker', 'Multicuiseur', 'Electric pressure multicooker', 'طباخة متعددة الوظائف'],
    ['waffle-maker', 'Gaufrier', 'Open waffle maker with square waffle plates', 'آلة وافل'],
    ['sandwich-maker', 'Appareil à croque-monsieur', 'Open toasted sandwich maker with triangular plates', 'آلة شطائر محمصة'],
    ['panini-grill', 'Grill à panini', 'Contact panini grill with ribbed plates', 'شواية بانيني'],
    ['raclette', 'Appareil à raclette', 'Raclette grill with little cheese pans', 'جهاز راكليت'],
    ['crepe-maker', 'Crêpière électrique', 'Round electric crepe maker with wooden spreader', 'آلة كريب كهربائية'],
  ] },
  { key: 'coffee-drinks', room: 'Cuisine', items: [
    ['capsule-machine', 'Cafetière à capsules', 'Compact coffee capsule machine', 'آلة قهوة بالكبسولات'],
    ['pod-machine', 'Cafetière à dosettes souples', 'Coffee machine for round soft paper pods', 'آلة قهوة بأكياس ورقية'],
    ['filter-coffee', 'Cafetière filtre', 'Drip filter coffee maker with glass carafe', 'آلة قهوة بالتقطير'],
    ['espresso-machine', 'Machine espresso à porte-filtre', 'Espresso machine with portafilter and steam wand', 'آلة إسبريسو بحامل فلتر'],
    ['bean-coffee', 'Machine à café à grains', 'Automatic bean-to-cup machine with top bean hopper', 'آلة قهوة بحبوب كاملة'],
    ['french-press', 'Cafetière à piston', 'Glass French press coffee maker', 'مكبس قهوة فرنسي'],
    ['moka-pot', 'Cafetière italienne', 'Octagonal stovetop moka coffee pot', 'إبريق قهوة موكا'],
    ['pour-over', 'Porte-filtre à café', 'Ceramic pour-over coffee dripper', 'قمع ترشيح قهوة'],
    ['coffee-grinder', 'Moulin à café', 'Electric coffee grinder', 'مطحنة قهوة'],
    ['milk-frother', 'Mousseur à lait', 'Electric jug milk frother', 'رغّاية حليب كهربائية'],
    ['electric-kettle', 'Bouilloire électrique', 'Electric kettle on its base', 'غلاية كهربائية'],
    ['stove-kettle', 'Bouilloire pour plaque', 'Stovetop whistling kettle', 'غلاية صفارة للموقد'],
    ['teapot', 'Théière', 'Ceramic teapot with lid', 'إبريق شاي خزفي'],
    ['moroccan-teapot', 'Théière marocaine', 'Polished silver Moroccan teapot with curved spout', 'براد شاي مغربي'],
    ['thermos', 'Carafe isotherme', 'Insulated vacuum coffee carafe', 'إبريق حراري'],
    ['citrus-juicer', 'Presse-agrumes électrique', 'Electric citrus juicer with exposed cone', 'عصارة حمضيات كهربائية'],
  ] },
  { key: 'cookware', room: 'Cuisine', items: [
    ['saucepan', 'Casserole', 'Stainless saucepan with long handle', 'قدر بمقبض طويل'],
    ['stockpot', 'Faitout', 'Stock pot with two handles and lid', 'قدر طبخ بغطاء'],
    ['frying-pan', 'Poêle antiadhésive', 'Nonstick frying pan', 'مقلاة غير لاصقة'],
    ['stainless-pan', 'Poêle inox', 'Shiny stainless steel frying pan', 'مقلاة فولاذ مقاوم للصدأ'],
    ['cast-iron-pan', 'Poêle en fonte', 'Heavy cast iron skillet', 'مقلاة حديد زهر'],
    ['wok', 'Wok', 'Deep round-bottom wok', 'مقلاة ووك'],
    ['saute-pan', 'Sauteuse', 'Deep straight-sided saute pan with lid', 'مقلاة عميقة بغطاء'],
    ['dutch-oven', 'Cocotte en fonte', 'Enameled cast iron Dutch oven', 'قدر حديد زهر مطلي'],
    ['pressure-cooker', 'Cocotte-minute', 'Stovetop pressure cooker with locking lid', 'قدر ضغط'],
    ['couscous-pot', 'Couscoussier', 'Two-tier stainless couscous steamer pot', 'كسكاس'],
    ['tagine', 'Plat à tajine', 'Terracotta Moroccan tagine with conical lid', 'طاجين فخاري'],
    ['griddle-pan', 'Poêle grill', 'Square ridged grill pan', 'مقلاة شواء مخططة'],
    ['crepe-pan', 'Poêle à crêpes', 'Very shallow round crepe pan', 'مقلاة كريب'],
    ['oven-dish', 'Plat à gratin', 'Rectangular ceramic oven dish', 'صينية فرن خزفية'],
    ['roasting-pan', 'Plat à rôtir', 'Metal roasting pan with rack', 'صينية تحمير بشبكة'],
    ['pot-lid', 'Couvercle de casserole', 'Glass pot lid with round knob', 'غطاء قدر زجاجي'],
  ] },
  { key: 'utensils', room: 'Cuisine', items: [
    ['chef-knife', 'Couteau de chef', 'Large chef kitchen knife', 'سكين طاهٍ'],
    ['bread-knife', 'Couteau à pain', 'Long serrated bread knife', 'سكين خبز مسنن'],
    ['paring-knife', 'Couteau d’office', 'Small paring knife', 'سكين تقشير صغير'],
    ['kitchen-scissors', 'Ciseaux de cuisine', 'Kitchen scissors', 'مقص مطبخ'],
    ['peeler', 'Économe', 'Vegetable peeler', 'مقشرة خضروات'],
    ['cutting-board', 'Planche à découper', 'Wooden chopping board', 'لوح تقطيع'],
    ['grater', 'Râpe', 'Four-sided box grater', 'مبشرة صندوقية'],
    ['ladle', 'Louche', 'Stainless soup ladle', 'مغرفة حساء'],
    ['spatula', 'Spatule', 'Flat silicone cooking spatula', 'ملعقة طبخ مسطحة'],
    ['slotted-spoon', 'Écumoire', 'Slotted skimmer spoon', 'ملعقة مثقبة'],
    ['wooden-spoon', 'Cuillère en bois', 'Wooden cooking spoon', 'ملعقة خشبية'],
    ['whisk', 'Fouet', 'Wire balloon whisk', 'مضرب يدوي'],
    ['tongs', 'Pince de cuisine', 'Kitchen serving tongs', 'ملقط مطبخ'],
    ['can-opener', 'Ouvre-boîte', 'Manual can opener', 'فتاحة علب'],
    ['corkscrew', 'Tire-bouchon', 'Winged corkscrew', 'فتاحة فلين'],
    ['bottle-opener', 'Décapsuleur', 'Simple metal bottle opener', 'فتاحة زجاجات'],
  ] },
  { key: 'tableware', room: 'Cuisine', items: [
    ['dinner-plate', 'Assiette plate', 'Large flat ceramic dinner plate', 'طبق طعام مسطح'],
    ['soup-plate', 'Assiette creuse', 'Deep rimmed soup plate', 'طبق حساء عميق'],
    ['dessert-plate', 'Assiette à dessert', 'Small ceramic dessert plate', 'طبق حلوى صغير'],
    ['bowl', 'Bol', 'Round breakfast bowl', 'وعاء إفطار'],
    ['salad-bowl', 'Saladier', 'Large glass salad bowl', 'وعاء سلطة كبير'],
    ['serving-platter', 'Plat de service', 'Oval ceramic serving platter', 'طبق تقديم بيضاوي'],
    ['mug', 'Mug', 'Ceramic coffee mug with handle', 'كوب خزفي بمقبض'],
    ['espresso-cup', 'Tasse à espresso', 'Small espresso cup and saucer', 'فنجان إسبريسو'],
    ['tea-cup', 'Tasse à thé', 'Tea cup and matching saucer', 'فنجان شاي وصحن'],
    ['water-glass', 'Verre à eau', 'Short clear water tumbler', 'كأس ماء'],
    ['wine-glass', 'Verre à vin', 'Stemmed wine glass', 'كأس نبيذ بساق'],
    ['champagne-flute', 'Flûte à champagne', 'Tall narrow champagne flute', 'كأس شمبانيا طويل'],
    ['tea-glass', 'Verre à thé marocain', 'Small Moroccan tea glass with gold rim', 'كأس شاي مغربي'],
    ['dinner-fork', 'Fourchette', 'Dinner fork with four tines', 'شوكة طعام'],
    ['dinner-knife', 'Couteau de table', 'Rounded dinner table knife', 'سكين مائدة'],
    ['spoon-set', 'Cuillère à soupe et petite cuillère', 'Tablespoon and teaspoon side by side showing size difference', 'ملعقة كبيرة وملعقة صغيرة'],
  ] },
  { key: 'bathroom', room: 'Salle de bain', items: [
    ['hairdryer', 'Sèche-cheveux', 'Handheld hairdryer', 'مجفف شعر'],
    ['hair-straightener', 'Lisseur à cheveux', 'Hair straightening iron', 'مكواة فرد الشعر'],
    ['bathroom-scale', 'Pèse-personne', 'Digital bathroom weighing scale', 'ميزان حمام'],
    ['magnifying-mirror', 'Miroir grossissant', 'Round magnifying mirror on stand', 'مرآة تكبير'],
    ['toilet-brush', 'Brosse WC', 'Toilet brush in holder', 'فرشاة مرحاض وحامل'],
    ['toilet-roll-holder', 'Porte-papier toilette', 'Freestanding toilet roll holder', 'حامل ورق مرحاض'],
    ['soap-dispenser', 'Distributeur de savon', 'Empty ceramic refillable soap dispenser', 'موزع صابون قابل للتعبئة'],
    ['soap-dish', 'Porte-savon', 'Ceramic soap dish', 'صحن صابون'],
    ['toothbrush-cup', 'Gobelet porte-brosses', 'Bathroom toothbrush tumbler', 'كوب فرش الأسنان'],
    ['shower-curtain', 'Rideau de douche', 'Shower curtain with rings', 'ستارة دش'],
    ['shower-squeegee', 'Raclette de douche', 'Handheld shower glass squeegee', 'ماسحة زجاج الدش'],
    ['shower-caddy', 'Étagère de douche', 'Hanging shower storage caddy', 'رف أدوات دش'],
    ['towel-rack', 'Porte-serviettes', 'Freestanding towel rack', 'حامل مناشف'],
    ['bathroom-bin', 'Poubelle de salle de bain', 'Small pedal bathroom bin', 'سلة حمام بدواسة'],
    ['non-slip-mat', 'Tapis antidérapant de douche', 'Rubber shower mat with suction cups', 'بساط دش مانع للانزلاق'],
    ['bath-tray', 'Plateau de baignoire', 'Expandable bamboo bathtub tray', 'رف بانيو من الخيزران'],
  ] },
  { key: 'laundry-cleaning', room: 'Buanderie', items: [
    ['front-washer', 'Lave-linge hublot', 'Front-loading washing machine', 'غسالة بتحميل أمامي'],
    ['top-washer', 'Lave-linge top', 'Top-loading washing machine with top lid', 'غسالة بتحميل علوي'],
    ['dryer', 'Sèche-linge', 'Tumble dryer with circular glass door and lower lint panel', 'مجفف ملابس'],
    ['washer-dryer', 'Lave-linge séchant', 'Combined washer dryer with two program dials', 'غسالة مع مجفف'],
    ['iron', 'Fer à repasser', 'Steam clothes iron', 'مكواة بخار'],
    ['steam-station', 'Centrale vapeur', 'Steam iron connected to large separate steam base', 'مكواة بمحطة بخار'],
    ['garment-steamer', 'Défroisseur', 'Handheld garment steamer', 'جهاز بخار للملابس'],
    ['ironing-board', 'Table à repasser', 'Folding ironing board', 'طاولة كي'],
    ['drying-rack', 'Étendoir à linge', 'Folding wing clothes drying rack', 'منشر ملابس'],
    ['laundry-basket', 'Panier à linge', 'Wicker laundry basket', 'سلة غسيل'],
    ['canister-vacuum', 'Aspirateur traîneau', 'Canister vacuum cleaner with hose', 'مكنسة كهربائية بخرطوم'],
    ['stick-vacuum', 'Aspirateur balai', 'Cordless stick vacuum cleaner', 'مكنسة عصا لاسلكية'],
    ['robot-vacuum', 'Aspirateur robot', 'Round robot vacuum with charging dock', 'مكنسة روبوت'],
    ['steam-mop', 'Balai vapeur', 'Upright steam mop', 'ممسحة بخار'],
    ['broom-dustpan', 'Balai et pelle', 'Broom and upright dustpan set', 'مكنسة يدوية ومجرود'],
    ['mop-bucket', 'Serpillière et seau', 'String mop with wringer bucket', 'ممسحة ودلو عصر'],
  ] },
  { key: 'lighting', room: 'Salon', items: [
    ['floor-lamp', 'Lampadaire', 'Tall floor lamp with fabric shade', 'مصباح أرضي'],
    ['table-lamp', 'Lampe à poser', 'Table lamp with ceramic base', 'مصباح طاولة'],
    ['bedside-lamp', 'Lampe de chevet', 'Small bedside lamp', 'مصباح بجانب السرير'],
    ['desk-lamp', 'Lampe de bureau', 'Adjustable articulated desk lamp', 'مصباح مكتب قابل للتعديل'],
    ['pendant-light', 'Suspension', 'Hanging pendant ceiling light', 'مصباح معلق'],
    ['chandelier', 'Lustre', 'Multi-arm chandelier', 'ثريا'],
    ['ceiling-light', 'Plafonnier', 'Round flush ceiling light', 'مصباح سقف دائري'],
    ['wall-light', 'Applique murale', 'Wall-mounted sconce', 'مصباح جداري'],
    ['reading-light', 'Liseuse', 'Flexible bedside reading light', 'مصباح قراءة مرن'],
    ['night-light', 'Veilleuse', 'Small plug-in night light', 'مصباح ليلي'],
    ['led-strip', 'Ruban LED', 'Coiled LED light strip with adapter', 'شريط إضاءة LED'],
    ['string-lights', 'Guirlande lumineuse', 'String of warm festoon light bulbs', 'سلسلة مصابيح'],
    ['lantern', 'Lanterne', 'Decorative Moroccan metal lantern', 'فانوس معدني'],
    ['solar-light', 'Lampe solaire de jardin', 'Solar garden stake light', 'مصباح حديقة شمسي'],
    ['portable-lamp', 'Lampe rechargeable', 'Portable rechargeable table lamp with handle', 'مصباح قابل للشحن'],
    ['flashlight', 'Lampe torche', 'Handheld flashlight', 'مصباح يدوي'],
  ] },
  { key: 'climate', room: 'Salon', items: [
    ['split-ac', 'Climatiseur mural', 'Wall mounted split air conditioner', 'مكيف جداري'],
    ['portable-ac', 'Climatiseur mobile', 'Portable air conditioner with exhaust hose', 'مكيف متنقل'],
    ['ceiling-fan', 'Ventilateur de plafond', 'Ceiling fan with three blades', 'مروحة سقف'],
    ['pedestal-fan', 'Ventilateur sur pied', 'Pedestal fan', 'مروحة عمودية'],
    ['desk-fan', 'Ventilateur de table', 'Small desk fan', 'مروحة طاولة'],
    ['tower-fan', 'Ventilateur colonne', 'Tall tower fan', 'مروحة برجية'],
    ['oil-heater', 'Radiateur bain d’huile', 'Oil-filled electric radiator on wheels', 'مدفأة زيت كهربائية'],
    ['fan-heater', 'Chauffage soufflant', 'Compact electric fan heater', 'مدفأة بمروحة'],
    ['panel-heater', 'Radiateur électrique mural', 'Flat wall panel heater', 'مدفأة كهربائية جدارية'],
    ['towel-warmer', 'Sèche-serviettes', 'Wall-mounted ladder towel radiator', 'مجفف مناشف جداري'],
    ['dehumidifier', 'Déshumidificateur', 'Portable dehumidifier with water tank', 'مزيل رطوبة'],
    ['humidifier', 'Humidificateur', 'Compact ultrasonic humidifier with visible mist', 'مرطب هواء'],
    ['air-purifier', 'Purificateur d’air', 'Cylindrical air purifier with perforated sides', 'منقي هواء'],
    ['thermostat', 'Thermostat', 'Wall thermostat with simple blank display', 'منظم حرارة'],
    ['water-heater', 'Chauffe-eau électrique', 'Wall mounted cylindrical electric water heater', 'سخان ماء كهربائي'],
    ['ac-remote', 'Télécommande de climatiseur', 'Air conditioner remote with LCD display', 'جهاز تحكم المكيف'],
  ] },
  { key: 'electronics', room: 'Salon', items: [
    ['television', 'Téléviseur', 'Flat screen television with stand', 'تلفاز مسطح'],
    ['tv-remote', 'Télécommande TV', 'Television remote with many buttons', 'جهاز تحكم التلفاز'],
    ['projector', 'Vidéoprojecteur', 'Compact video projector', 'جهاز عرض'],
    ['projector-screen', 'Écran de projection', 'Tripod projection screen', 'شاشة عرض على حامل'],
    ['soundbar', 'Barre de son', 'Slim soundbar speaker', 'مكبر صوت شريطي'],
    ['bluetooth-speaker', 'Enceinte Bluetooth', 'Portable Bluetooth speaker', 'مكبر صوت بلوتوث'],
    ['smart-speaker', 'Enceinte connectée', 'Small smart speaker with fabric cover', 'مكبر صوت ذكي'],
    ['radio', 'Radio', 'Compact tabletop radio with antenna', 'راديو'],
    ['alarm-clock', 'Réveil', 'Digital bedside alarm clock', 'منبه رقمي'],
    ['wifi-router', 'Routeur Wi-Fi', 'Wifi router with antennas', 'جهاز توجيه واي فاي'],
    ['wifi-extender', 'Répéteur Wi-Fi', 'Plug-in wifi range extender', 'مقوي إشارة واي فاي'],
    ['tv-box', 'Boîtier TV', 'Streaming television box and remote', 'جهاز بث تلفزيوني'],
    ['games-console', 'Console de jeux', 'Unbranded video game console and controller', 'جهاز ألعاب'],
    ['game-controller', 'Manette de jeu', 'Standalone game controller', 'يد تحكم ألعاب'],
    ['monitor', 'Écran d’ordinateur', 'Computer monitor on adjustable stand', 'شاشة حاسوب'],
    ['printer', 'Imprimante', 'Compact home printer with paper tray', 'طابعة منزلية'],
  ] },
  { key: 'safety-access', room: 'Entree', items: [
    ['smoke-detector', 'Détecteur de fumée', 'Round ceiling smoke alarm', 'كاشف دخان'],
    ['co-detector', 'Détecteur de monoxyde de carbone', 'Rectangular carbon monoxide alarm with display', 'كاشف أول أكسيد الكربون'],
    ['gas-detector', 'Détecteur de gaz', 'Plug-in gas detector with vent slots', 'كاشف غاز'],
    ['water-leak-sensor', 'Détecteur de fuite d’eau', 'Small water leak sensor with cable probe', 'حساس تسرب ماء'],
    ['fire-extinguisher', 'Extincteur', 'Small red fire extinguisher', 'مطفأة حريق'],
    ['fire-blanket', 'Couverture anti-feu', 'Fire blanket pouch with two pull straps', 'بطانية إطفاء'],
    ['first-aid-kit', 'Trousse de secours', 'Open first aid case with bandages', 'حقيبة إسعافات أولية'],
    ['safe', 'Coffre-fort', 'Small electronic hotel safe', 'خزنة إلكترونية'],
    ['key-safe', 'Boîte à clés', 'Wall mounted numeric combination key safe', 'صندوق مفاتيح برمز'],
    ['smart-lock', 'Serrure connectée', 'Electronic smart door lock and handle', 'قفل باب ذكي'],
    ['key-set', 'Jeu de clés', 'Metal house keys on keyring', 'مجموعة مفاتيح'],
    ['access-fob', 'Badge d’accès', 'Contactless key fob', 'شارة دخول إلكترونية'],
    ['intercom', 'Interphone', 'Wall intercom handset', 'هاتف باب داخلي'],
    ['video-intercom', 'Visiophone', 'Wall video door intercom monitor', 'جهاز اتصال مرئي للباب'],
    ['doorbell', 'Sonnette', 'Wireless doorbell button and chime', 'جرس باب لاسلكي'],
    ['doorstop', 'Butée de porte', 'Rubber wedge doorstop', 'مصد باب'],
  ] },
  { key: 'baby', room: 'Chambre', items: [
    ['cot', 'Lit bébé à barreaux', 'Wooden baby cot with vertical slats', 'سرير رضيع بقضبان'],
    ['travel-cot', 'Lit parapluie', 'Mesh travel cot', 'سرير سفر للرضيع'],
    ['bassinet', 'Berceau', 'Small rocking bassinet', 'مهد رضيع'],
    ['high-chair', 'Chaise haute', 'Baby high chair with tray', 'كرسي طعام مرتفع للطفل'],
    ['booster-seat', 'Rehausseur de chaise', 'Child dining booster seat with straps', 'مقعد رفع للطفل'],
    ['changing-table', 'Table à langer', 'Baby changing table with lower shelf', 'طاولة تغيير حفاضات'],
    ['changing-mat', 'Matelas à langer', 'Padded baby changing mat', 'وسادة تغيير حفاضات'],
    ['baby-bath', 'Baignoire bébé', 'Small plastic baby bathtub', 'حوض استحمام للرضيع'],
    ['baby-gate', 'Barrière de sécurité', 'Child safety stair gate', 'حاجز أمان للأطفال'],
    ['bed-rail', 'Barrière de lit', 'Mesh toddler bed guard rail', 'حاجز سرير للأطفال'],
    ['baby-monitor', 'Babyphone', 'Baby monitor camera and parent screen', 'جهاز مراقبة الطفل'],
    ['bottle-warmer', 'Chauffe-biberon', 'Electric baby bottle warmer', 'جهاز تدفئة الرضاعات'],
    ['bottle-sterilizer', 'Stérilisateur de biberons', 'Baby bottle steam sterilizer', 'معقم رضاعات'],
    ['potty', 'Pot enfant', 'Small toddler potty', 'نونية طفل'],
    ['toilet-reducer', 'Réducteur de toilette', 'Child toilet seat reducer', 'مقعد مرحاض للأطفال'],
    ['stroller', 'Poussette', 'Compact folding baby stroller', 'عربة أطفال'],
  ] },
  { key: 'outdoor-furniture', room: 'Exterieur', items: [
    ['garden-table', 'Table de jardin', 'Outdoor garden dining table', 'طاولة حديقة'],
    ['garden-chair', 'Chaise de jardin', 'Outdoor garden chair', 'كرسي حديقة'],
    ['outdoor-sofa', 'Canapé de jardin', 'Woven outdoor sofa with cushions', 'أريكة حديقة'],
    ['garden-bench', 'Banc de jardin', 'Slatted garden bench', 'مقعد حديقة طويل'],
    ['sun-lounger', 'Bain de soleil', 'Reclining sun lounger', 'كرسي استلقاء شمسي'],
    ['deckchair', 'Chilienne', 'Folding canvas sling deck chair', 'كرسي قماشي قابل للطي'],
    ['hammock', 'Hamac', 'Hammock on freestanding frame', 'أرجوحة شبكية'],
    ['hanging-chair', 'Fauteuil suspendu', 'Hanging egg chair on stand', 'كرسي معلق'],
    ['parasol', 'Parasol droit', 'Upright garden parasol', 'مظلة حديقة مستقيمة'],
    ['cantilever-parasol', 'Parasol déporté', 'Cantilever parasol with side support', 'مظلة جانبية'],
    ['parasol-base', 'Pied de parasol', 'Weighted parasol base', 'قاعدة مظلة'],
    ['shade-sail', 'Voile d’ombrage', 'Triangular shade sail stretched on three poles', 'شراع تظليل'],
    ['charcoal-bbq', 'Barbecue à charbon', 'Round charcoal kettle barbecue', 'شواية فحم'],
    ['gas-bbq', 'Barbecue à gaz', 'Gas barbecue grill with lid and wheels', 'شواية غاز'],
    ['electric-bbq', 'Barbecue électrique', 'Compact electric tabletop barbecue', 'شواية كهربائية'],
    ['plancha', 'Plancha', 'Flat top plancha grill', 'صفيحة شواء مسطحة'],
  ] },
  { key: 'garden-pool', room: 'Exterieur', items: [
    ['garden-hose', 'Tuyau d’arrosage', 'Coiled garden hose with spray nozzle', 'خرطوم ري'],
    ['watering-can', 'Arrosoir', 'Metal watering can', 'مرش ماء'],
    ['hose-reel', 'Dévidoir de tuyau', 'Garden hose reel on wheels', 'بكرة خرطوم'],
    ['garden-tools', 'Outils de jardin', 'Hand garden trowel and small rake', 'أدوات بستنة يدوية'],
    ['lawnmower', 'Tondeuse', 'Push lawn mower', 'جزازة عشب'],
    ['pool-net', 'Épuisette de piscine', 'Pool skimmer net on telescopic pole', 'شبكة تنظيف مسبح'],
    ['pool-vacuum', 'Robot de piscine', 'Pool cleaning robot', 'روبوت تنظيف مسبح'],
    ['pool-cover', 'Bâche de piscine', 'Rolled blue pool cover', 'غطاء مسبح ملفوف'],
    ['pool-float', 'Bouée', 'Inflatable swimming ring', 'عوامة سباحة'],
    ['pool-noodle', 'Frite de piscine', 'Two foam pool noodles', 'عوامات إسفنجية طويلة'],
    ['life-ring', 'Bouée de sauvetage', 'Orange life saving ring with rope', 'طوق نجاة'],
    ['outdoor-shower', 'Douche extérieure', 'Freestanding outdoor shower column', 'دش خارجي'],
    ['hot-tub', 'Jacuzzi', 'Square outdoor hot tub', 'حوض جاكوزي'],
    ['fire-pit', 'Brasero', 'Metal garden fire pit bowl', 'موقد نار خارجي'],
    ['patio-heater', 'Chauffage de terrasse', 'Tall patio heater', 'مدفأة شرفة'],
    ['garden-storage-box', 'Coffre de jardin', 'Outdoor deck storage box', 'صندوق تخزين خارجي'],
  ] },
  { key: 'leisure', room: 'Salon', items: [
    ['board-game', 'Jeu de société', 'Open board game with pawns and dice, no writing', 'لعبة لوحية'],
    ['playing-cards', 'Jeu de cartes', 'Deck of playing cards fanned out', 'أوراق لعب'],
    ['chess-set', 'Jeu d’échecs', 'Chess board with pieces', 'طقم شطرنج'],
    ['dominoes', 'Dominos', 'Wooden box of domino tiles', 'لعبة دومينو'],
    ['puzzle', 'Puzzle', 'Unbranded jigsaw puzzle with scattered pieces', 'أحجية تركيب'],
    ['books', 'Livres', 'Three hardcover books with blank spines', 'مجموعة كتب'],
    ['yoga-mat', 'Tapis de yoga', 'Rolled yoga exercise mat', 'حصيرة يوغا'],
    ['dumbbells', 'Haltères', 'Pair of small dumbbells', 'أثقال يدوية'],
    ['exercise-bike', 'Vélo d’appartement', 'Stationary exercise bicycle', 'دراجة تمارين'],
    ['bicycle', 'Vélo', 'Adult city bicycle', 'دراجة هوائية'],
    ['bicycle-helmet', 'Casque de vélo', 'Cycling helmet', 'خوذة دراجة'],
    ['table-tennis', 'Raquettes de ping-pong', 'Two table tennis paddles and ball', 'مضارب تنس طاولة'],
    ['badminton', 'Raquettes de badminton', 'Two badminton rackets and shuttlecock', 'مضارب ريشة'],
    ['petanque', 'Jeu de pétanque', 'Three metal petanque balls in case', 'كرات بيتانك'],
    ['beach-umbrella', 'Parasol de plage', 'Folded beach umbrella in carry bag', 'مظلة شاطئ'],
    ['cooler', 'Glacière', 'Insulated picnic cooler box', 'صندوق تبريد متنقل'],
  ] },
  { key: 'storage', room: 'Rangement', items: [
    ['wardrobe', 'Armoire à portes battantes', 'Wooden wardrobe with hinged doors', 'خزانة ملابس بأبواب مفصلية'],
    ['sliding-wardrobe', 'Armoire à portes coulissantes', 'Wardrobe with sliding doors', 'خزانة بأبواب منزلقة'],
    ['clothes-rack', 'Portant à vêtements', 'Open clothes rack with rail', 'حامل ملابس مفتوح'],
    ['wooden-hanger', 'Cintre en bois', 'Wooden clothes hanger', 'علاقة ملابس خشبية'],
    ['clip-hanger', 'Cintre à pinces', 'Trouser hanger with two clips', 'علاقة ملابس بمشابك'],
    ['wall-hooks', 'Patères murales', 'Wall mounted row of coat hooks', 'خطافات حائط'],
    ['coat-stand', 'Porte-manteau sur pied', 'Freestanding coat stand', 'حامل معاطف'],
    ['shoe-rack', 'Étagère à chaussures', 'Open shoe storage rack', 'رف أحذية'],
    ['shoe-cabinet', 'Meuble à chaussures', 'Tilt-out shoe cabinet', 'خزانة أحذية'],
    ['luggage-rack', 'Porte-bagages', 'Folding hotel luggage rack with straps', 'حامل حقائب'],
    ['storage-basket', 'Panier de rangement', 'Woven storage basket', 'سلة تخزين'],
    ['storage-box', 'Boîte de rangement', 'Clear storage box with lid', 'صندوق تخزين بغطاء'],
    ['underbed-box', 'Boîte sous le lit', 'Low flat under-bed storage box', 'صندوق تخزين تحت السرير'],
    ['drawer-organizer', 'Organiseur de tiroir', 'Compartment drawer organizer', 'منظم أدراج'],
    ['wall-shelf', 'Étagère murale', 'Floating wooden wall shelf', 'رف جداري'],
    ['umbrella-stand', 'Porte-parapluies', 'Tall umbrella stand', 'حامل مظلات'],
  ] },
  { key: 'tools', room: 'Rangement', items: [
    ['step-stool', 'Marchepied', 'Folding two-step stool', 'سلم صغير بدرجتين'],
    ['stepladder', 'Escabeau', 'Four-step folding stepladder', 'سلم منزلي قابل للطي'],
    ['toolbox', 'Boîte à outils', 'Open toolbox with basic tools', 'صندوق أدوات'],
    ['screwdriver-set', 'Tournevis', 'Flat and Phillips screwdrivers side by side', 'مفكات مسطحة وصليبية'],
    ['hammer', 'Marteau', 'Claw hammer', 'مطرقة'],
    ['pliers', 'Pince universelle', 'Combination pliers', 'كماشة متعددة الاستعمال'],
    ['adjustable-wrench', 'Clé à molette', 'Adjustable wrench', 'مفتاح ربط قابل للتعديل'],
    ['tape-measure', 'Mètre ruban', 'Retractable tape measure', 'شريط قياس'],
    ['drill', 'Perceuse-visseuse', 'Cordless drill with battery', 'مثقاب ومفك لاسلكي'],
    ['extension-cord', 'Rallonge électrique', 'Coiled electrical extension cord', 'سلك تمديد كهربائي'],
    ['power-strip', 'Multiprise', 'European multi-socket power strip', 'مشترك كهربائي'],
    ['travel-adapter', 'Adaptateur de prise universel', 'Universal travel plug adapter', 'محول مقابس عالمي'],
    ['usb-charger', 'Chargeur USB', 'USB wall charger with two ports', 'شاحن USB جداري'],
    ['usb-c-cable', 'Câble USB-C', 'Coiled cable with two USB-C connectors clearly visible', 'كابل USB-C'],
    ['lightning-cable', 'Câble Lightning', 'Coiled cable with slim Lightning connector clearly visible', 'كابل لايتنينغ'],
    ['hdmi-cable', 'Câble HDMI', 'Coiled HDMI cable with wide trapezoid connectors', 'كابل HDMI'],
  ] },
  { key: 'accessibility-pets', room: 'Autre', items: [
    ['shower-chair', 'Chaise de douche', 'Accessible shower chair with backrest', 'كرسي استحمام'],
    ['bath-seat', 'Siège de baignoire', 'Bath board seat spanning bathtub width', 'مقعد بانيو'],
    ['grab-bar', 'Barre d’appui', 'Wall grab rail', 'قضيب مساعدة جداري'],
    ['raised-toilet', 'Rehausseur WC', 'Raised toilet seat with arm supports', 'مقعد مرحاض مرتفع بمساند'],
    ['portable-ramp', 'Rampe d’accès amovible', 'Portable wheelchair access ramp', 'منحدر وصول متنقل'],
    ['wheelchair', 'Fauteuil roulant', 'Manual wheelchair', 'كرسي متحرك'],
    ['walking-frame', 'Déambulateur', 'Four-wheel walking frame with seat', 'مشاية بعجلات'],
    ['non-slip-step', 'Marche antidérapante', 'Wide low non-slip access step', 'درجة مانعة للانزلاق'],
    ['pet-bowl', 'Gamelle', 'Stainless pet food bowl', 'وعاء طعام للحيوان'],
    ['pet-double-bowl', 'Double gamelle', 'Double pet food and water bowls in stand', 'وعاء مزدوج للحيوان'],
    ['dog-bed', 'Panier pour chien', 'Padded oval dog bed', 'سرير كلب'],
    ['cat-bed', 'Couchage pour chat', 'Enclosed felt cat cave bed', 'بيت نوم للقط'],
    ['litter-tray', 'Bac à litière', 'Open cat litter tray', 'صندوق رمل قطط مفتوح'],
    ['covered-litter', 'Maison de toilette pour chat', 'Covered cat litter box with flap', 'صندوق رمل قطط مغلق'],
    ['pet-carrier', 'Caisse de transport', 'Pet travel carrier with front grille', 'صندوق نقل حيوانات'],
    ['scratching-post', 'Griffoir pour chat', 'Cat scratching post', 'عمود خدش للقطط'],
  ] },
  { key: 'kitchen-extras', room: 'Cuisine', items: [
    ['colander', 'Passoire', 'Stainless kitchen colander', 'مصفاة مطبخ'],
    ['fine-sieve', 'Chinois et tamis', 'Fine mesh conical kitchen sieve', 'مصفاة دقيقة مخروطية'],
    ['mixing-bowl', 'Cul-de-poule', 'Stainless mixing bowl', 'وعاء خلط فولاذي'],
    ['measuring-jug', 'Verre doseur', 'Transparent measuring jug with handle', 'إبريق قياس'],
    ['kitchen-scale', 'Balance de cuisine', 'Flat digital kitchen scale', 'ميزان مطبخ'],
    ['rolling-pin', 'Rouleau à pâtisserie', 'Wooden rolling pin', 'نشابة عجين'],
    ['cake-tin', 'Moule à gâteau', 'Round springform cake tin', 'قالب كعك دائري'],
    ['loaf-tin', 'Moule à cake', 'Rectangular loaf baking tin', 'قالب كعك مستطيل'],
    ['muffin-tin', 'Moule à muffins', 'Six-cup muffin baking tin', 'قالب مافن'],
    ['baking-tray', 'Plaque de cuisson', 'Flat metal oven baking tray', 'صفيحة خبز معدنية'],
    ['salad-spinner', 'Essoreuse à salade', 'Salad spinner with inner basket visible', 'مجفف سلطة'],
    ['food-container', 'Boîte alimentaire', 'Glass food storage container with lid', 'علبة حفظ طعام'],
    ['water-jug', 'Carafe à eau', 'Clear glass water carafe', 'إبريق ماء زجاجي'],
    ['filter-jug', 'Carafe filtrante', 'Water filter pitcher with inner filter chamber', 'إبريق ترشيح ماء'],
    ['dish-rack', 'Égouttoir à vaisselle', 'Countertop dish drying rack', 'رف تجفيف صحون'],
    ['kitchen-bin', 'Poubelle de cuisine', 'Tall kitchen pedal bin', 'سلة مطبخ بدواسة'],
  ] },
  { key: 'decor', room: 'Salon', items: [
    ['wall-mirror', 'Miroir mural', 'Round wall mirror', 'مرآة جدارية'],
    ['full-length-mirror', 'Miroir sur pied', 'Full length standing mirror', 'مرآة طويلة على حامل'],
    ['wall-clock', 'Horloge murale', 'Minimal round wall clock', 'ساعة حائط'],
    ['picture-frame', 'Cadre photo', 'Small tabletop picture frame with neutral abstract insert', 'إطار صورة'],
    ['wall-art', 'Tableau décoratif', 'Framed abstract wall art in muted earthy colors', 'لوحة فنية جدارية'],
    ['vase', 'Vase', 'Ceramic flower vase', 'مزهرية خزفية'],
    ['plant-pot', 'Cache-pot', 'Empty ceramic planter pot', 'وعاء نبات خزفي'],
    ['indoor-plant', 'Plante d’intérieur', 'Small potted leafy houseplant', 'نبتة منزلية'],
    ['artificial-plant', 'Plante artificielle', 'Artificial potted plant with visibly uniform plastic leaves', 'نبتة صناعية'],
    ['candle-holder', 'Bougeoir', 'Brass candle holder without candle', 'حامل شموع'],
    ['reed-diffuser', 'Diffuseur à bâtonnets', 'Glass reed diffuser bottle with wooden sticks', 'ناشر عطر بأعواد'],
    ['essential-oil-diffuser', 'Diffuseur électrique', 'Electric essential oil diffuser with light mist', 'ناشر عطر كهربائي'],
    ['serving-tray', 'Plateau', 'Wooden serving tray with handles', 'صينية تقديم'],
    ['magazine-rack', 'Porte-revues', 'Freestanding magazine rack', 'حامل مجلات'],
    ['room-divider', 'Paravent', 'Three-panel folding room divider', 'فاصل غرف قابل للطي'],
    ['decorative-basket', 'Corbeille décorative', 'Shallow decorative woven basket', 'سلة زينة منسوجة'],
  ] },
  { key: 'fixtures', room: 'Salle de bain', items: [
    ["toilet","WC sur pied","Freestanding toilet with cistern","مرحاض أرضي بخزان"],
    ["wall-toilet","WC suspendu","Wall-hung toilet bowl with concealed flush plate","مرحاض معلق"],
    ["washbasin","Lavabo sur colonne","Pedestal bathroom washbasin","مغسلة بعمود"],
    ["vessel-basin","Vasque à poser","Round countertop vessel washbasin","حوض مغسلة فوق السطح"],
    ["vanity-unit","Meuble sous-vasque","Bathroom vanity cabinet with integrated washbasin","خزانة حمام مع مغسلة"],
    ["bathtub","Baignoire","Freestanding oval bathtub","حوض استحمام"],
    ["shower-enclosure","Cabine de douche","Glass corner shower enclosure with tray","كابينة استحمام زجاجية"],
    ["shower-screen","Paroi de douche","Single frameless shower glass screen with support arm","حاجز دش زجاجي"],
    ["shower-column","Colonne de douche","Chrome shower column with rainfall head and handheld spray","عمود دش"],
    ["shower-head","Pommeau de douche","Handheld shower head with flexible hose","رأس دش يدوي"],
    ["basin-tap","Mitigeur de lavabo","Single lever bathroom basin mixer tap","خلاط مغسلة"],
    ["bath-tap","Mitigeur de baignoire","Wall-mounted bathtub mixer tap with spout","خلاط بانيو جداري"],
    ["kitchen-sink","Évier de cuisine","Stainless steel double bowl kitchen sink","حوض مطبخ مزدوج"],
    ["kitchen-tap","Robinet de cuisine","Tall gooseneck kitchen mixer tap","صنبور مطبخ"],
    ["towel-hook","Crochet de salle de bain","Single chrome bathroom towel hook","خطاف منشفة"],
    ["bathroom-cabinet","Armoire de toilette","Wall bathroom cabinet with mirrored doors","خزانة حمام بمرآة"],
  ] },
  { key: 'tableware-details', room: 'Cuisine', items: [
    ["tablespoon","Cuillère à soupe","One stainless steel tablespoon, large oval bowl","ملعقة طعام"],
    ["teaspoon","Cuillère à café","One small stainless steel teaspoon with short handle","ملعقة شاي صغيرة"],
    ["dessert-fork","Fourchette à dessert","One small three-pronged dessert fork","شوكة حلوى"],
    ["steak-knife","Couteau à steak","One serrated steak knife with dark wooden handle","سكين لحم"],
    ["butter-knife","Couteau à beurre","One short blunt butter spreading knife","سكين زبدة"],
    ["serving-spoon","Cuillère de service","One large stainless serving spoon with deep bowl","ملعقة تقديم كبيرة"],
    ["salad-servers","Couverts à salade","Wooden salad fork and spoon pair","أدوات تقديم سلطة"],
    ["chopsticks","Baguettes","One pair of bamboo chopsticks","عيدان طعام"],
    ["red-wine-glass","Verre à vin rouge","Large wide round-bowl red wine glass, empty","كأس نبيذ أحمر واسع"],
    ["white-wine-glass","Verre à vin blanc","Narrow tulip-bowl white wine glass, empty","كأس نبيذ أبيض ضيق"],
    ["champagne-coupe","Coupe à champagne","Wide shallow champagne coupe glass, empty","كأس شامبانيا عريض"],
    ["beer-glass","Verre à bière","Tall tapered beer pint glass, empty","كأس بيرة طويل"],
    ["cocktail-glass","Verre à cocktail","V-shaped martini cocktail glass, empty","كأس كوكتيل"],
    ["shot-glass","Verre à liqueur","Small thick-bottom shot glass, empty","كأس صغير"],
    ["child-plate","Assiette enfant","Silicone toddler plate with three divided compartments","طبق أطفال مقسم"],
    ["child-cutlery","Couverts enfant","Small child fork and spoon with thick silicone handles","أدوات مائدة أطفال"],
  ] },
];
