package com.clenzy.marketplace.service;

import com.clenzy.marketplace.model.MarketplaceQuoteRequest;
import com.clenzy.marketplace.model.QuoteRequestStatus;
import com.clenzy.marketplace.repository.MarketplaceQuoteRequestRepository;
import org.hibernate.cfg.Configuration;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.data.jpa.repository.support.JpaRepositoryFactory;
import java.util.UUID;
import static org.assertj.core.api.Assertions.assertThat;

/** Validation des requêtes sur un schéma isolé construit avec les migrations réelles du module. */
@EnabledIfSystemProperty(named = "baitly.test.jdbc", matches = "jdbc:postgresql:.*")
class MarketplaceQuoteDiscussionPostgresTest {
    org.springframework.jdbc.datasource.SingleConnectionDataSource source;
    org.springframework.jdbc.core.JdbcTemplate db;
    String schema;
    @org.junit.jupiter.api.BeforeEach void migrateFixture() throws Exception {
        source=new org.springframework.jdbc.datasource.SingleConnectionDataSource(System.getProperty("baitly.test.jdbc"),
                System.getProperty("baitly.test.user","postgres"),"",true);
        db=new org.springframework.jdbc.core.JdbcTemplate(source);
        schema="baitly_discussion_"+UUID.randomUUID().toString().replace("-","");
        db.execute("CREATE SCHEMA "+schema);
        db.execute("SET search_path TO "+schema);
        db.execute("CREATE TABLE marketplace_providers(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,public_ref uuid,display_name text,email text)");
        db.execute("CREATE TABLE teams(id bigint PRIMARY KEY)");
        db.execute("CREATE TABLE organizations(id bigint PRIMARY KEY)");
        db.execute("CREATE TABLE interventions(id bigint PRIMARY KEY,service_request_id bigint)");
        db.execute("CREATE TABLE service_requests(id bigint PRIMARY KEY)");
        db.execute("CREATE TABLE service_quotes(id bigint PRIMARY KEY,status text)");
        db.execute("CREATE TABLE service_quote_cancellations(quote_id bigint PRIMARY KEY,intervention_id bigint NOT NULL)");
        for (String file:java.util.List.of("0432__marketplace_quote_requests.sql","0434__marketplace_quote_discussions.sql",
                "0458__service_quote_replacements.sql","0473__service_assignment_proposals.sql")) {
            try (var input=getClass().getResourceAsStream("/db/changelog/changes/"+file)) {
                db.execute(new String(input.readAllBytes(),java.nio.charset.StandardCharsets.UTF_8));
            }
        }
    }
    @org.junit.jupiter.api.AfterEach void cleanupFixture() {
        if (db!=null && schema!=null) db.execute("DROP SCHEMA "+schema+" CASCADE");
        if (source!=null) source.destroy();
    }

    @Test
    void pendingPublicationIsDurableAndFailureBackoffDoesNotBlockOtherRequests() {
        try (var sessions = new Configuration().addAnnotatedClass(MarketplaceQuoteRequest.class)
                 .setProperty("hibernate.connection.url", System.getProperty("baitly.test.jdbc")
                        +(System.getProperty("baitly.test.jdbc").contains("?")?"&":"?")+"currentSchema="+schema)
                .setProperty("hibernate.connection.username", System.getProperty("baitly.test.user", "postgres"))
                .setProperty("hibernate.hbm2ddl.auto", "validate").buildSessionFactory();
             var em = sessions.createEntityManager()) {
            em.getTransaction().begin();
            Long providerId = ((Number) em.createNativeQuery("INSERT INTO marketplace_providers (public_ref, display_name, email) VALUES (:ref, 'Baitly test', 'test@example.invalid') RETURNING id")
                    .setParameter("ref", UUID.randomUUID()).getSingleResult()).longValue();
            var first = request(providerId); var second = request(providerId);
            em.persist(first); em.persist(second); em.flush();
            Long firstId = first.getId(), secondId = second.getId();
            em.getTransaction().commit();
            var repository = new JpaRepositoryFactory(em).getRepository(MarketplaceQuoteRequestRepository.class);
            try {
                assertThat(repository.findPendingDiscussions()).contains(firstId, secondId);
                em.getTransaction().begin();
                repository.deferDiscussion(firstId);
                var locked = repository.findForDiscussion(secondId).orElseThrow();
                locked.setDiscussionPublishedStatus(QuoteRequestStatus.SENT);
                em.getTransaction().commit();
                assertThat(repository.findPendingDiscussions()).doesNotContain(firstId, secondId);
                em.getTransaction().begin();
                locked = repository.findForDiscussion(secondId).orElseThrow();
                locked.setStatus(QuoteRequestStatus.QUOTED);
                em.getTransaction().commit();
                assertThat(repository.findPendingDiscussions()).contains(secondId).doesNotContain(firstId);
            } finally {
                if (em.getTransaction().isActive()) em.getTransaction().rollback();
                em.getTransaction().begin();
                em.createNativeQuery("DELETE FROM marketplace_quote_requests WHERE id IN (:first, :second)")
                        .setParameter("first", firstId).setParameter("second", secondId).executeUpdate();
                em.createNativeQuery("DELETE FROM marketplace_providers WHERE id = :id").setParameter("id", providerId).executeUpdate();
                em.getTransaction().commit();
            }
        }
    }

    private MarketplaceQuoteRequest request(Long providerId) {
        var request = new MarketplaceQuoteRequest(); request.setProviderId(providerId);
        request.setRequesterOrganizationId(7L); request.setTitle("Test publication");
        request.setStatus(QuoteRequestStatus.SENT);
        request.setCreatedAt(java.time.LocalDateTime.now()); request.setUpdatedAt(java.time.LocalDateTime.now());
        return request;
    }
}
